<p><span style="color: rgb(0,255,255)"><span style="font-family: Arial"><span style="font-size: 10pt"><strong>Thời gian v&agrave;o cửa</strong></span></span></span></p>
<p style="text-align: center"><span style="font-family: Arial"><span style="font-size: 10pt; color: black"><strong><img onload="ResizeImages(this) " height="448" alt="" width="717" src="http://mu.gate.vn/images/Editor/image/website/Su%20kien%20trong%20game/image081.jpg" /></strong></span></span></p>
<p><span style="color: rgb(0,255,255)"><span style="font-family: Arial"><span style="font-size: 10pt"><strong>Quy tắc li&ecirc;n quan đến việc v&agrave;o cửa</strong></span></span></span></p>
<p>&nbsp;</p>
<div style="margin: 0in 5.5pt 0pt 28.35pt"><span style="color: rgb(255,255,255)"><span><span style="font-family: Arial"><span style="font-size: 10pt"><strong>Người tham dự</strong></span></span></span></span></div>
<div style="margin: 0in 5.5pt 0pt 28.35pt"><span style="color: rgb(153,204,255)"><span style="font-family: Arial">&nbsp;</span></span></div>
<div style="margin: 0in 5.5pt 0pt 42.55pt"><span style="color: rgb(153,204,255)"><span style="font-family: Arial"><font size="2">1)</font><span style="font: 7pt 'Times New Roman'; font-size-adjust: none; font-stretch: normal">&nbsp;&nbsp;&nbsp; </span><font size="2">&iacute;t nhất l&agrave; 4 người&nbsp;~&nbsp;nhiều nhất l&agrave; 20 người v&agrave;o theo thứ tự trước sau.</font></span></span></div>
<div style="margin: 0in 5.5pt 0pt 42.55pt"><span style="color: rgb(153,204,255)"><span style="font-family: Arial">&nbsp;</span></span></div>
<div style="margin: 0in 5.5pt 0pt 42.55pt"><span style="color: rgb(153,204,255)"><span style="font-family: Arial"><font size="2">2)</font><span style="font: 7pt 'Times New Roman'; font-size-adjust: none; font-stretch: normal">&nbsp;&nbsp;&nbsp; </span><font size="2">Trong 24h mỗi người chỉ c&oacute; thể tham gia 6 lần.</font></span></span></div>
<div style="margin: 0in 5.5pt 0pt 42.55pt"><span style="color: rgb(153,204,255)"><span style="font-family: Arial">&nbsp;</span></span></div>
<div style="margin: 0in 5.5pt 0pt 42.55pt"><span style="color: rgb(153,204,255)"><span style="font-family: Arial"><font size="2">3)</font><span style="font: 7pt 'Times New Roman'; font-size-adjust: none; font-stretch: normal">&nbsp;&nbsp;&nbsp; </span><font size="2">Trong trường hợp kh&ocirc;ng đủ người theo y&ecirc;u cầu sẽ được đưa về Devias</font></span></span></div>
<div style="margin: 0in 5.5pt 0pt 42.55pt"><span style="color: rgb(153,204,255)"><span style="font-family: Arial">&nbsp;</span></span></div>
<div style="margin: 0in 5.5pt 0pt 42.55pt"><span style="color: rgb(153,204,255)"><span style="font-family: Arial"><font size="2">4)</font><span style="font: 7pt 'Times New Roman'; font-size-adjust: none; font-stretch: normal">&nbsp;&nbsp;&nbsp; </span><span><font size="2">C&oacute; thể v&agrave;o cửa th&ocirc;ng qua &ldquo;Mira ju&rdquo; ở tọa độ (224,52) Devias.</font></span></span></span></div>
<div style="margin: 0in 5.5pt 0pt 42.55pt"><span style="font-family: Arial">&nbsp;</span></div>
<div style="margin: 0in 5.5pt 0pt 42.55pt; text-align: center"><span style="font-family: Arial"><span style="color: black"><font size="2"><img onload="ResizeImages(this) " height="310" alt="" width="244" src="http://mu.gate.vn/images/Editor/image/website/Su%20kien%20trong%20game/image082.jpg" /></font></span></span></div>
<div style="margin: 0in 5.5pt 0pt 42.55pt"><span style="font-family: Arial">&nbsp;</span></div>
<div style="margin: 0in 5.5pt 0pt 42.55pt">&nbsp;</div>
<div style="margin: 0in 5.5pt 0pt 42.55pt"><span style="color: rgb(153,204,255)"><span style="font-family: Arial">&nbsp;C</span><span style="font-family: Arial"><span style="font-size: 10pt">&oacute; thể c&oacute; được th&ocirc;ng tin về con người hiện tại v&agrave; đền ch&ugrave;a đ&uacute;ng với cấp bậc character.</span></span></span></div>
<div style="margin: 0in 5.5pt 0pt 0.75in; text-indent: -0.25in">&nbsp;</div>
<div style="margin: 0in 5.5pt 0pt; text-indent: 0in"><span style="color: rgb(153,204,255)"><span style="font-family: Arial">&nbsp;</span></span></div>
<div style="margin: 0in 5.5pt 0pt; text-indent: 0in"><span style="color: rgb(0,255,255)"><span><strong><span style="font-family: Arial"><span style="font-size: 10pt; line-height: 115%">Đấu trường</span></span></strong></span></span></div>
<div style="margin: 0in 5.5pt 0pt; text-indent: 0in">&nbsp;</div>
<div style="margin: 0in 5.5pt 0pt; text-indent: 0in"><span style="color: rgb(255,255,255)"><strong><span><span style="font-family: Arial"><span style="font-size: 10pt; line-height: 115%">1. Thời gian tiến h&agrave;nh</span></span></span></strong></span></div>
<p><span style="font-family: Arial">&nbsp;</span></p>
<div align="center">
  <center>
    <table cellspacing="0" cellpadding="0" border="1" style="border-right: medium none; border-top: medium none; background: rgb(146,205,220); margin: auto auto auto 4.2pt; border-left: medium none; width: 423.75pt; border-bottom: medium none; border-collapse: collapse; -moz-background-clip: -moz-initial; -moz-background-origin: -moz-initial; -moz-background-inline-policy: -moz-initial">
      <tbody>
        <tr style="height: 11.25pt">
          <td width="151" style="border-right: windowtext 1pt solid; padding-right: 4.95pt; border-top: windowtext 1pt solid; padding-left: 4.95pt; padding-bottom: 0in; border-left: windowtext 1pt solid; width: 113.1pt; padding-top: 0in; border-bottom: windowtext 1pt solid; height: 11.25pt; background-color: transparent"><div style="margin: 0in 4.5pt 10pt" align="center"><span style="font-family: Arial"><b><span style="font-size: 10pt; color: rgb(0,32,96); line-height: 115%">Sau khi v&agrave;o ph&ograve;ng ch</span></b><b><span style="font-size: 10pt; color: rgb(0,32,96); line-height: 115%">ờ</span></b></span></div></td>
          <td width="126" style="border-right: windowtext 1pt solid; padding-right: 4.95pt; border-top: windowtext 1pt solid; padding-left: 4.95pt; padding-bottom: 0in; border-left: rgb(236,233,216); width: 94.65pt; padding-top: 0in; border-bottom: windowtext 1pt solid; height: 11.25pt; background-color: transparent"><div style="margin: 0in 0in 10pt" align="center"><span style="font-family: Arial"><b><span style="font-size: 10pt; color: rgb(0,32,96); line-height: 115%">Ch</span></b><b><span style="font-size: 10pt; color: rgb(0,32,96); line-height: 115%">ờ</span></b><b><span style="font-size: 10pt; color: rgb(0,32,96); line-height: 115%"> nơi xuất ph&aacute;t</span></b></span></div></td>
          <td width="72" style="border-right: windowtext 1pt solid; padding-right: 4.95pt; border-top: windowtext 1pt solid; padding-left: 4.95pt; padding-bottom: 0in; border-left: rgb(236,233,216); width: 0.75in; padding-top: 0in; border-bottom: windowtext 1pt solid; height: 11.25pt; background-color: transparent"><div style="margin: 0in 0in 10pt" align="center"><span style="font-family: Arial"><b><span style="font-size: 10pt; color: rgb(0,32,96); line-height: 115%">Th</span></b><b><span style="font-size: 10pt; color: rgb(0,32,96); line-height: 115%">ờ</span></b><b><span style="font-size: 10pt; color: rgb(0,32,96); line-height: 115%">i gian chiến đấu</span></b></span></div></td>
          <td width="132" style="border-right: windowtext 1pt solid; padding-right: 4.95pt; border-top: windowtext 1pt solid; padding-left: 4.95pt; padding-bottom: 0in; border-left: rgb(236,233,216); width: 99pt; padding-top: 0in; border-bottom: windowtext 1pt solid; height: 11.25pt; background-color: transparent"><div style="margin: 0in 0in 10pt" align="center"><span style="font-family: Arial"><b><span style="font-size: 10pt; color: rgb(0,32,96); line-height: 115%">Ho&agrave;n tất event v&agrave; giải thưởng</span></b></span></div></td>
          <td width="84" style="border-right: windowtext 1pt solid; padding-right: 4.95pt; border-top: windowtext 1pt solid; padding-left: 4.95pt; padding-bottom: 0in; border-left: rgb(236,233,216); width: 63pt; padding-top: 0in; border-bottom: windowtext 1pt solid; height: 11.25pt; background-color: transparent"><div style="margin: 0in 0in 10pt"><span style="font-family: Arial"><b><span style="font-size: 10pt; color: rgb(0,32,96); line-height: 115%">Tổng cộng</span></b></span></div></td>
        </tr>
        <tr style="height: 11.25pt">
          <td nowrap="nowrap" width="151" style="border-right: windowtext 1pt solid; padding-right: 4.95pt; border-top: rgb(236,233,216); padding-left: 4.95pt; padding-bottom: 0in; border-left: windowtext 1pt solid; width: 113.1pt; padding-top: 0in; border-bottom: windowtext 1pt solid; height: 11.25pt; background-color: transparent"><div style="margin: 0in 0in 10pt" align="center"><span style="font-family: Arial"><span style="font-size: 10pt; color: rgb(0,32,96); line-height: 115%">5ph&uacute;t</span></span></div></td>
          <td nowrap="nowrap" width="126" style="border-right: windowtext 1pt solid; padding-right: 4.95pt; border-top: rgb(236,233,216); padding-left: 4.95pt; padding-bottom: 0in; border-left: rgb(236,233,216); width: 94.65pt; padding-top: 0in; border-bottom: windowtext 1pt solid; height: 11.25pt; background-color: transparent"><div style="margin: 0in 0in 10pt" align="center"><span style="font-family: Arial"><span style="font-size: 10pt; color: rgb(0,32,96); line-height: 115%">1 ph&uacute;t</span></span></div></td>
          <td nowrap="nowrap" width="72" style="border-right: windowtext 1pt solid; padding-right: 4.95pt; border-top: rgb(236,233,216); padding-left: 4.95pt; padding-bottom: 0in; border-left: rgb(236,233,216); width: 0.75in; padding-top: 0in; border-bottom: windowtext 1pt solid; height: 11.25pt; background-color: transparent"><div style="margin: 0in 0in 10pt" align="center"><span style="font-family: Arial"><span style="font-size: 10pt; color: rgb(0,32,96); line-height: 115%">15 ph&uacute;t</span></span></div></td>
          <td nowrap="nowrap" width="132" style="border-right: windowtext 1pt solid; padding-right: 4.95pt; border-top: rgb(236,233,216); padding-left: 4.95pt; padding-bottom: 0in; border-left: rgb(236,233,216); width: 99pt; padding-top: 0in; border-bottom: windowtext 1pt solid; height: 11.25pt; background-color: transparent"><div style="margin: 0in 0in 10pt" align="center"><span style="font-family: Arial"><span style="font-size: 10pt; color: rgb(0,32,96); line-height: 115%">4 ph&uacute;t</span></span></div></td>
          <td nowrap="nowrap" width="84" style="border-right: windowtext 1pt solid; padding-right: 4.95pt; border-top: rgb(236,233,216); padding-left: 4.95pt; padding-bottom: 0in; border-left: rgb(236,233,216); width: 63pt; padding-top: 0in; border-bottom: windowtext 1pt solid; height: 11.25pt; background-color: transparent"><div style="margin: 0in 0in 10pt" align="center"><span style="font-family: Arial"><span style="font-size: 10pt; color: rgb(0,32,96); line-height: 115%">25 ph&uacute;t</span></span></div></td>
        </tr>
      </tbody>
    </table>
  </center>
</div>
<p><span style="font-family: Arial">&nbsp;</span></p>
<div style="margin: 0in 5.5pt 0pt 31.5pt; text-indent: -0.25in"><span style="color: rgb(153,204,255)"><span style="font-family: Arial"><span style="font-size: 10pt">1)<span style="font: 7pt 'Times New Roman'; font-size-adjust: none; font-stretch: normal">&nbsp;&nbsp;&nbsp; </span></span><span style="font-size: 10pt">Th</span><span style="font-size: 10pt">ờ</span><span style="font-size: 10pt">i gian c&oacute; thể v&agrave;o cửa tất cả l&agrave; 5 ph&uacute;t v&agrave; nếu 5 ph&uacute;t tr&ocirc;i qua th&igrave; kh&ocirc;ng v&agrave;o cửa.</span></span></span></div>
<div style="margin: 0in 5.5pt 0pt 31.5pt; text-indent: -0.25in"><span style="color: rgb(153,204,255)">&nbsp;</span></div>
<div style="margin: 0in 5.5pt 0pt 31.5pt; text-indent: -0.25in"><span style="color: rgb(153,204,255)"><span style="font-family: Arial"><span style="font-size: 10pt">2)<span style="font: 7pt 'Times New Roman'; font-size-adjust: none; font-stretch: normal">&nbsp;&nbsp;&nbsp; </span></span><span style="font-size: 10pt">Trong tr</span><span style="font-size: 10pt">ường hợp </span><span style="font-size: 10pt">số người v&agrave;o đ&atilde; đầy th&igrave; kh&ocirc;ng thể v&agrave;o được nữa.</span></span></span></div>
<div style="margin: 0in 5.5pt 0pt 31.5pt; text-indent: -0.25in"><span style="color: rgb(153,204,255)">&nbsp;</span></div>
<div style="margin: 0in 5.5pt 0pt 31.5pt; text-indent: -0.25in"><span style="color: rgb(153,204,255)"><span style="font-family: Arial"><span style="font-size: 10pt">3)<span style="font: 7pt 'Times New Roman'; font-size-adjust: none; font-stretch: normal">&nbsp;&nbsp;&nbsp; </span></span><span style="font-size: 10pt">Sau khi v&agrave;o trong th&igrave; người chơi chia ra l&agrave;m 2 b&ecirc;n.</span></span></span></div>
<div style="margin: 0in 5.5pt 0pt 31.5pt; text-indent: -0.25in"><span style="color: rgb(153,204,255)">&nbsp;</span></div>
<div style="margin: 0in 5.5pt 0pt 31.5pt; text-indent: -0.25in"><span style="color: rgb(153,204,255)"><span style="font-family: Arial"><span style="font-size: 10pt">4)<span style="font: 7pt 'Times New Roman'; font-size-adjust: none; font-stretch: normal">&nbsp;&nbsp;&nbsp; </span></span><span style="font-size: 10pt">Sau khi qua từng b&ecirc;n sẽ được v&agrave;o nh&oacute;m v&agrave; kh&ocirc;ng thể bỏ nh&oacute;m được.</span></span></span></div>
<div style="margin: 0in 5.5pt 0pt 31.5pt; text-indent: -0.25in"><span style="color: rgb(153,204,255)">&nbsp;</span></div>
<div style="margin: 0in 5.5pt 0pt 31.5pt; text-indent: -0.25in"><span style="color: rgb(153,204,255)"><span style="font-family: Arial"><span style="font-size: 10pt">5)<span style="font: 7pt 'Times New Roman'; font-size-adjust: none; font-stretch: normal">&nbsp;&nbsp;&nbsp; </span></span><span style="font-size: 10pt">Sẽ kh&ocirc;ng hiển thị được c&aacute;nh của nh&acirc;n vật.</span></span></span></div>
<div style="margin: 0in 4.5pt 10pt"><span style="color: rgb(153,204,255)"><span style="font-family: Arial">&nbsp;</span></span></div>
<div style="margin: 0in 4.5pt 10pt"><span style="color: rgb(255,255,255)"><span><span style="font-family: Arial"><span style="font-size: 10pt"><strong>2. Phương ph&aacute;p tiến h&agrave;nh</strong></span></span></span></span></div>
<div style="margin: 0in 5.5pt 0pt 27.5pt"><span style="color: rgb(153,204,255)"><span style="font-family: Arial"><span style="font-size: 10pt">&nbsp;1) Hết thời gian chờ 2 b&ecirc;n đi v&agrave;o đền thờ.</span></span></span></div>
<div style="margin: 0in 5.5pt 0pt 27.5pt"><span style="color: rgb(153,204,255)">&nbsp;</span></div>
<div style="margin: 0in 5.5pt 0pt 27.5pt"><span style="color: rgb(153,204,255)"><span style="font-family: Arial"><span style="font-size: 10pt">&nbsp;2) Mục ti&ecirc;u l&agrave; phải bảo vệ bảo vật xuất hiện random 1 trong 2 b&ecirc;n.</span></span></span></div>
<div style="margin: 0in 5.5pt 0pt 27.5pt"><span style="color: rgb(153,204,255)">&nbsp;</span></div>
<div style="margin: 0in 5.5pt 0pt 27.5pt"><span style="color: rgb(153,204,255)"><span style="font-family: Arial"><span style="font-size: 10pt">&nbsp;3) Nếu click v&agrave;o pho tượng th&igrave; phải chờ 10 gi&acirc;y để lấy được bảo vật.</span></span></span></div>
<div style="margin: 0in 5.5pt 0pt 27.5pt"><span style="color: rgb(153,204,255)">&nbsp;</span></div>
<div style="margin: 0in 5.5pt 0pt 27.5pt"><span style="color: rgb(153,204,255)"><span style="font-family: Arial"><span style="font-size: 10pt">&nbsp;&nbsp;&nbsp; </span><span style="font-size: 10pt">※</span><span style="font-size: 10pt"> Kh&ocirc;ng được di chuyển nếu kh&ocirc;ng trạng th&aacute;i chờ lấy bảo vật sẽ bị hũy bỏ.</span></span></span></div>
<div style="margin: 0in 5.5pt 0pt 27.5pt"><span style="color: rgb(153,204,255)">&nbsp;</span></div>
<div style="margin: 0in 5.5pt 0pt 27.5pt"><span style="color: rgb(153,204,255)"><span style="font-family: Arial"><span style="font-size: 10pt">&nbsp;4) Người chơi lấy được bảo vật sẽ di chuyển chậm v&agrave; xuất hiện vị tr&iacute; của m&igrave;nh tr&ecirc;n bản đồ.</span></span></span></div>
<div style="margin: 0in 5.5pt 0pt 27.5pt"><span style="color: rgb(153,204,255)">&nbsp;</span></div>
<div style="margin: 0in 5.5pt 0pt 27.5pt"><span style="color: rgb(153,204,255)"><span style="font-family: Arial"><span style="font-size: 10pt">&nbsp;5) Đi đến nơi cất bảo vật, nếu chưa nhận được điểm th&igrave; kh&ocirc;ng thể hồi sinh lại.</span></span></span></div>
<div style="margin: 0in 5.5pt 0pt 27.5pt"><span style="color: rgb(153,204,255)">&nbsp;</span></div>
<div style="margin: 0in 5.5pt 0pt 27.5pt"><span style="color: rgb(153,204,255)"><span style="font-family: Arial"><span style="font-size: 10pt">&nbsp;6) Trường hợp nh&acirc;n vật giữ bảo vật bị chết th&igrave; bảo vật sẽ rơi tại chổ v&agrave; bất kỳ người n&agrave;o kh&aacute;c đều c&oacute; thể lấy được. </span></span><span style="font-family: Arial"><span style="font-size: 10pt">Trong tr</span><span style="font-size: 10pt">ường hợp kh&ocirc;ng c&oacute; ai nhận được</span><span style="font-size: 10pt">, bảo vật sẽ biến mất v&agrave; xuất hiện một c&aacute;ch random ở pho tượng đ&aacute;.</span></span></span></div>
<div style="margin: 0in 5.5pt 0pt 27.5pt"><span style="color: rgb(153,204,255)">&nbsp;</span></div>
<div style="margin: 0in 5.5pt 0pt 27.5pt"><span style="color: rgb(153,204,255)"><span style="font-family: Arial"><span style="font-size: 10pt">&nbsp;7) Tuyệt chi&ecirc;u nghi binh</span></span></span></div>
<div style="margin: 0in 5.5pt 0pt 27.5pt"><span style="color: rgb(153,204,255)">&nbsp;</span></div>
<div style="margin: 0in 5.5pt 0pt 27.5pt"><span style="color: rgb(153,204,255)"><span style="font-family: Arial"><span style="font-size: 10pt">&nbsp;&nbsp;&nbsp; - Chỉ c&oacute; thể sử dụng b&ecirc;n trong đền thờ.</span></span></span></div>
<div style="margin: 0in 5.5pt 0pt 27.5pt"><span style="color: rgb(153,204,255)">&nbsp;</span></div>
<div style="margin: 0in 5.5pt 0pt 27.5pt"><span style="color: rgb(153,204,255)"><span style="font-family: Arial"><span style="font-size: 10pt">&nbsp;&nbsp;&nbsp; - Khi nh&acirc;n vật tử vong, to&agrave;n bộ số điểm t&iacute;ch lũy bị trở lại như l&uacute;c đầu v&agrave; khi nh&acirc;n vật được hồi sinh sẽ nhận được 10 point (t&iacute;ch lũy l</span><span style="font-size: 10pt">ớn nhất l&agrave; </span><span style="font-size: 10pt">90 point)</span></span></span></div>
<div style="margin: 0in 5.5pt 0pt 27.5pt"><span style="color: rgb(153,204,255)">&nbsp;</span></div>
<div style="margin: 0in 5.5pt 0pt 27.5pt"><span style="color: rgb(153,204,255)"><span style="font-family: Arial"><span style="font-size: 10pt">&nbsp;&nbsp;&nbsp; - Nh&acirc;n vật sau khi tử vong sẽ được hồi sinh ở vị tr&iacute; bắt đầu chiến đấu v&agrave; c&acirc;u thần ch&uacute; bảo vệ c&oacute; t&aacute;c dụng tự động trong 10 gi&acirc;y</span></span></span></div>
<div style="margin: 0in 5.5pt 0pt 27.5pt"><span style="color: rgb(153,204,255)">&nbsp;</span></div>
<div style="margin: 0in 5.5pt 0pt 27.5pt"><span style="color: rgb(153,204,255)"><span style="font-family: Arial"><span style="font-size: 10pt">&nbsp;&nbsp;&nbsp; - L</span><span style="font-size: 10pt">ựa chọn tuyệt chi&ecirc;u</span><span style="font-size: 10pt">: Lăng n&uacute;t giữa chuột</span></span></span></div>
<div style="margin: 0in 5.5pt 0pt 27.5pt"><span style="color: rgb(153,204,255)">&nbsp;</span></div>
<div style="margin: 0in 5.5pt 0pt 27.5pt"><span style="color: rgb(153,204,255)"><span style="font-family: Arial"><span style="font-size: 10pt">&nbsp;&nbsp;&nbsp; - Sử dụng tuyệt chi&ecirc;u: Shift + click phải chuột</span></span></span></div>
<p style="text-align: center"><span style="font-family: Arial">&nbsp;</span></p>
<div align="center">
  <center>
    <table cellspacing="0" cellpadding="0" border="1" style="border-right: medium none; border-top: medium none; background: rgb(146,205,220); border-left: medium none; border-bottom: medium none; border-collapse: collapse; -moz-background-clip: -moz-initial; -moz-background-origin: -moz-initial; -moz-background-inline-policy: -moz-initial">
      <tbody>
        <tr>
          <td width="96" style="border-right: windowtext 1pt solid; padding-right: 5.4pt; border-top: windowtext 1pt solid; padding-left: 5.4pt; padding-bottom: 0in; border-left: windowtext 1pt solid; width: 1in; padding-top: 0in; border-bottom: windowtext 1pt solid; background-color: transparent"><div style="margin: 0in 5.5pt 0pt 0in" align="center"><span style="font-family: Arial"><b><span style="font-size: 10pt; color: rgb(0,32,96)">Name</span></b></span></div></td>
          <td width="298" style="border-right: windowtext 1pt solid; padding-right: 5.4pt; border-top: windowtext 1pt solid; padding-left: 5.4pt; padding-bottom: 0in; border-left: rgb(236,233,216); width: 223.65pt; padding-top: 0in; border-bottom: windowtext 1pt solid; background-color: transparent"><div style="margin: 0in 5.5pt 0pt 0in" align="center"><span style="font-family: Arial"><b><span style="font-size: 10pt; color: rgb(0,32,96)">Hiệu quả</span></b></span></div></td>
          <td valign="top" width="84" style="border-right: windowtext 1pt solid; padding-right: 5.4pt; border-top: windowtext 1pt solid; padding-left: 5.4pt; padding-bottom: 0in; border-left: rgb(236,233,216); width: 63pt; padding-top: 0in; border-bottom: windowtext 1pt solid; background-color: transparent"><div style="margin: 0in 5.5pt 0pt 0in" align="center"><span style="font-family: Arial"><b><span style="font-size: 10pt; color: rgb(0,32,96)">Kill Count</span></b></span></div></td>
          <td valign="top" width="77" style="border-right: windowtext 1pt solid; padding-right: 5.4pt; border-top: windowtext 1pt solid; padding-left: 5.4pt; padding-bottom: 0in; border-left: rgb(236,233,216); width: 58pt; padding-top: 0in; border-bottom: windowtext 1pt solid; background-color: transparent"><div style="margin: 0in 5.5pt 0pt 0in" align="center"><span style="font-family: Arial"><b><span style="font-size: 10pt; color: rgb(0,32,96)">Th</span></b><b><span style="font-size: 10pt; color: rgb(0,32,96)">ời gian duy tr&igrave;</span></b></span></div></td>
        </tr>
        <tr>
          <td width="96" style="border-right: windowtext 1pt solid; padding-right: 5.4pt; border-top: rgb(236,233,216); padding-left: 5.4pt; padding-bottom: 0in; border-left: windowtext 1pt solid; width: 1in; padding-top: 0in; border-bottom: windowtext 1pt solid; background-color: transparent"><div style="margin: 0in 5.5pt 0pt 0in"><span style="font-family: Arial"><span style="font-size: 10pt; color: rgb(0,32,96)">Thần ch&uacute; bảo vệ</span></span></div></td>
          <td width="298" style="border-right: windowtext 1pt solid; padding-right: 5.4pt; border-top: rgb(236,233,216); padding-left: 5.4pt; padding-bottom: 0in; border-left: rgb(236,233,216); width: 223.65pt; padding-top: 0in; border-bottom: windowtext 1pt solid; background-color: transparent"><div style="margin: 0in 5.5pt 0pt 0in"><span style="font-family: Arial"><span style="font-size: 10pt; color: rgb(0,32,96)">Tạo ra sự bảo vệ trong nhất thời v&agrave; hấp thụ 100% damage</span></span></div></td>
          <td valign="top" width="84" style="border-right: windowtext 1pt solid; padding-right: 5.4pt; border-top: rgb(236,233,216); padding-left: 5.4pt; padding-bottom: 0in; border-left: rgb(236,233,216); width: 63pt; padding-top: 0in; border-bottom: windowtext 1pt solid; background-color: transparent"><div style="margin: 0in 5.5pt 0pt 0in" align="center"><span style="font-family: Arial"><span style="font-size: 10pt; color: rgb(0,32,96)">5</span></span></div></td>
          <td width="77" style="border-right: windowtext 1pt solid; padding-right: 5.4pt; border-top: rgb(236,233,216); padding-left: 5.4pt; padding-bottom: 0in; border-left: rgb(236,233,216); width: 58pt; padding-top: 0in; border-bottom: windowtext 1pt solid; background-color: transparent"><div style="margin: 0in 5.5pt 0pt 0in" align="center"><span style="font-family: Arial"><span style="font-size: 10pt; color: rgb(0,32,96)">15&nbsp;gi&acirc;y</span></span></div></td>
        </tr>
        <tr>
          <td width="96" style="border-right: windowtext 1pt solid; padding-right: 5.4pt; border-top: rgb(236,233,216); padding-left: 5.4pt; padding-bottom: 0in; border-left: windowtext 1pt solid; width: 1in; padding-top: 0in; border-bottom: windowtext 1pt solid; background-color: transparent"><div style="margin: 0in 5.5pt 0pt 0in" align="center"><span style="font-family: Arial"><span style="font-size: 10pt; color: rgb(0,32,96)">Thần ch&uacute;</span></span></div>
              <div style="margin: 0in 5.5pt 0pt 0in" align="center"><span style="font-family: Arial"><span style="font-size: 10pt; color: rgb(0,32,96)">&nbsp;Đ&oacute;ng băng</span></span></div></td>
          <td width="298" style="border-right: windowtext 1pt solid; padding-right: 5.4pt; border-top: rgb(236,233,216); padding-left: 5.4pt; padding-bottom: 0in; border-left: rgb(236,233,216); width: 223.65pt; padding-top: 0in; border-bottom: windowtext 1pt solid; background-color: transparent"><div style="margin: 0in 5.5pt 0pt 0in"><span style="font-family: Arial"><span style="font-size: 10pt; color: rgb(0,32,96)">L&agrave;m mất khả năng di chuyển của character trong nhất thời</span></span></div></td>
          <td valign="top" width="84" style="border-right: windowtext 1pt solid; padding-right: 5.4pt; border-top: rgb(236,233,216); padding-left: 5.4pt; padding-bottom: 0in; border-left: rgb(236,233,216); width: 63pt; padding-top: 0in; border-bottom: windowtext 1pt solid; background-color: transparent"><div style="margin: 0in 5.5pt 0pt 0in" align="center"><span style="font-family: Arial"><span style="font-size: 10pt; color: rgb(0,32,96)">5</span></span></div></td>
          <td width="77" style="border-right: windowtext 1pt solid; padding-right: 5.4pt; border-top: rgb(236,233,216); padding-left: 5.4pt; padding-bottom: 0in; border-left: rgb(236,233,216); width: 58pt; padding-top: 0in; border-bottom: windowtext 1pt solid; background-color: transparent"><div style="margin: 0in 5.5pt 0pt 0in" align="center"><span style="font-family: Arial"><span style="font-size: 10pt; color: rgb(0,32,96)">15 gi&acirc;y</span></span></div></td>
        </tr>
        <tr>
          <td width="96" style="border-right: windowtext 1pt solid; padding-right: 5.4pt; border-top: rgb(236,233,216); padding-left: 5.4pt; padding-bottom: 0in; border-left: windowtext 1pt solid; width: 1in; padding-top: 0in; border-bottom: windowtext 1pt solid; background-color: transparent"><div style="margin: 0in 5.5pt 0pt 0in" align="center"><span style="font-family: Arial"><span style="font-size: 10pt; color: rgb(0,32,96)">Thần ch&uacute; </span></span></div>
              <div style="margin: 0in 5.5pt 0pt 0in" align="center"><span style="font-family: Arial"><span style="font-size: 10pt; color: rgb(0,32,96)">Dịch chuyển</span></span></div></td>
          <td width="298" style="border-right: windowtext 1pt solid; padding-right: 5.4pt; border-top: rgb(236,233,216); padding-left: 5.4pt; padding-bottom: 0in; border-left: rgb(236,233,216); width: 223.65pt; padding-top: 0in; border-bottom: windowtext 1pt solid; background-color: transparent"><div style="margin: 0in 5.5pt 0pt 0in"><span style="font-family: Arial"><span style="font-size: 10pt; color: rgb(0,32,96)">Di chuyển đến vị tr&iacute; hiện tại của character đ&atilde; nhận được bảo vật</span></span></div></td>
          <td valign="top" width="84" style="border-right: windowtext 1pt solid; padding-right: 5.4pt; border-top: rgb(236,233,216); padding-left: 5.4pt; padding-bottom: 0in; border-left: rgb(236,233,216); width: 63pt; padding-top: 0in; border-bottom: windowtext 1pt solid; background-color: transparent"><div style="margin: 0in 5.5pt 0pt 0in" align="center"><span style="font-family: Arial"><span style="font-size: 10pt; color: rgb(0,32,96)">10</span></span></div></td>
          <td width="77" style="border-right: windowtext 1pt solid; padding-right: 5.4pt; border-top: rgb(236,233,216); padding-left: 5.4pt; padding-bottom: 0in; border-left: rgb(236,233,216); width: 58pt; padding-top: 0in; border-bottom: windowtext 1pt solid; background-color: transparent"><div style="margin: 0in 5.5pt 0pt 0in" align="center"><span style="font-family: Arial"><span style="font-size: 10pt; color: rgb(0,32,96)">-</span></span></div></td>
        </tr>
        <tr>
          <td width="96" style="border-right: windowtext 1pt solid; padding-right: 5.4pt; border-top: rgb(236,233,216); padding-left: 5.4pt; padding-bottom: 0in; border-left: windowtext 1pt solid; width: 1in; padding-top: 0in; border-bottom: windowtext 1pt solid; background-color: transparent"><div style="margin: 0in 5.5pt 0pt 0in" align="center"><span style="font-family: Arial"><span style="font-size: 10pt; color: rgb(0,32,96)">Giảm ph&ograve;ng thủ </span></span></div></td>
          <td width="298" style="border-right: windowtext 1pt solid; padding-right: 5.4pt; border-top: rgb(236,233,216); padding-left: 5.4pt; padding-bottom: 0in; border-left: rgb(236,233,216); width: 223.65pt; padding-top: 0in; border-bottom: windowtext 1pt solid; background-color: transparent"><div style="margin: 0in 5.5pt 0pt 0in"><span style="font-family: Arial"><span style="font-size: 10pt; color: rgb(0,32,96)">L&agrave;m giảm 50% khả năng ph&ograve;ng thủ hiện tại của đối phương</span></span></div></td>
          <td valign="top" width="84" style="border-right: windowtext 1pt solid; padding-right: 5.4pt; border-top: rgb(236,233,216); padding-left: 5.4pt; padding-bottom: 0in; border-left: rgb(236,233,216); width: 63pt; padding-top: 0in; border-bottom: windowtext 1pt solid; background-color: transparent"><div style="margin: 0in 5.5pt 0pt 0in" align="center"><span style="font-family: Arial"><span style="font-size: 10pt; color: rgb(0,32,96)">5</span></span></div></td>
          <td width="77" style="border-right: windowtext 1pt solid; padding-right: 5.4pt; border-top: rgb(236,233,216); padding-left: 5.4pt; padding-bottom: 0in; border-left: rgb(236,233,216); width: 58pt; padding-top: 0in; border-bottom: windowtext 1pt solid; background-color: transparent"><div style="margin: 0in 5.5pt 0pt 0in" align="center"><span style="font-family: Arial"><span style="font-size: 10pt; color: rgb(0,32,96)">-</span></span></div></td>
        </tr>
      </tbody>
    </table>
  </center>
</div>
<p><span style="font-family: Arial">&nbsp;</span></p>
<p><span style="color: rgb(153,204,255)"><span style="font-family: Arial"><span style="font-size: 10pt"><span style="font: 7pt 'Times New Roman'; font-size-adjust: none; font-stretch: normal">&nbsp; </span></span><span style="font-size: 10pt">Đ</span><span style="font-size: 10pt">ượ</span><span style="font-size: 10pt">c Kill Poin</span></span></span></p>
<p style="text-align: center"> </p>
<center>
  <table cellspacing="0" cellpadding="0" border="1" style="border-right: medium none; border-top: medium none; background: rgb(146,205,220); margin: auto auto auto 1.45in; border-left: medium none; border-bottom: medium none; border-collapse: collapse; -moz-background-clip: -moz-initial; -moz-background-origin: -moz-initial; -moz-background-inline-policy: -moz-initial">
    <tbody>
      <tr>
        <td valign="top" width="226" style="border-right: windowtext 1pt solid; padding-right: 5.4pt; border-top: windowtext 1pt solid; padding-left: 5.4pt; padding-bottom: 0in; border-left: windowtext 1pt solid; width: 169.85pt; padding-top: 0in; border-bottom: windowtext 1pt solid; background-color: transparent"><div style="margin: 0in 5.5pt 0pt 0in; text-align: center"><span style="font-family: Arial"><b><span style="font-size: 10pt; color: black">Đối tượng</span></b></span></div></td>
        <td valign="top" width="230" style="border-right: windowtext 1pt solid; padding-right: 5.4pt; border-top: windowtext 1pt solid; padding-left: 5.4pt; padding-bottom: 0in; border-left: rgb(236,233,216); width: 172.15pt; padding-top: 0in; border-bottom: windowtext 1pt solid; background-color: transparent"><div style="margin: 0in 5.5pt 0pt 0in; text-align: center"><span style="font-family: Arial"><b><span style="font-size: 10pt; color: black">Point c&oacute; thể nhận được</span></b></span></div></td>
      </tr>
      <tr>
        <td valign="top" width="226" style="border-right: windowtext 1pt solid; padding-right: 5.4pt; border-top: rgb(236,233,216); padding-left: 5.4pt; padding-bottom: 0in; border-left: windowtext 1pt solid; width: 169.85pt; padding-top: 0in; border-bottom: windowtext 1pt solid; background-color: transparent"><div style="margin: 0in 5.5pt 0pt 0in; text-align: center"><span style="font-family: Arial"><span style="font-size: 10pt; color: black">Monster</span></span></div></td>
        <td valign="top" width="230" style="border-right: windowtext 1pt solid; padding-right: 5.4pt; border-top: rgb(236,233,216); padding-left: 5.4pt; padding-bottom: 0in; border-left: rgb(236,233,216); width: 172.15pt; padding-top: 0in; border-bottom: windowtext 1pt solid; background-color: transparent"><div style="margin: 0in 5.5pt 0pt 0in; text-align: center"><span style="font-family: Arial"><span style="font-size: 10pt; color: black">2</span></span></div></td>
      </tr>
      <tr>
        <td valign="top" width="226" style="border-right: windowtext 1pt solid; padding-right: 5.4pt; border-top: rgb(236,233,216); padding-left: 5.4pt; padding-bottom: 0in; border-left: windowtext 1pt solid; width: 169.85pt; padding-top: 0in; border-bottom: windowtext 1pt solid; background-color: transparent"><div style="margin: 0in 5.5pt 0pt 0in; text-align: center"><span style="font-family: Arial"><span style="font-size: 10pt; color: black">Player</span></span></div></td>
        <td valign="top" width="230" style="border-right: windowtext 1pt solid; padding-right: 5.4pt; border-top: rgb(236,233,216); padding-left: 5.4pt; padding-bottom: 0in; border-left: rgb(236,233,216); width: 172.15pt; padding-top: 0in; border-bottom: windowtext 1pt solid; background-color: transparent"><div style="margin: 0in 5.5pt 0pt 0in; text-align: center"><span style="font-family: Arial"><span style="font-size: 10pt; color: black">5</span></span></div></td>
      </tr>
    </tbody>
  </table>
</center>
</p>
<p style="text-align: center"><span style="font-family: Arial"><span style="color: black"><font size="2"><img onload="ResizeImages(this) " alt="" style="width: 200px; height: 62px" src="http://mu.gate.vn/images/Editor/image/website/Su%20kien%20trong%20game/image083.jpg" /></font></span></span></p>
<p style="text-align: left"><span style="color: rgb(153,204,255)"><span style="font-family: Arial"><span><font size="2"><span style="font-size: 10pt; line-height: 115%">T</span><span style="font-size: 10pt; line-height: 115%" lang="vi" xml:lang="vi">ừ</span><span style="font-size: 10pt; line-height: 115%"> b&ecirc;n tr&aacute;i sang: Icon tuyệt chi&ecirc;u , Kill Count y&ecirc;u cầu để sử dụng tuyệt chi&ecirc;u, Kill Count hiện tại của nh&acirc;n vật</span></font></span></span></span></p>
<p style="text-align: center"><span style="font-family: Arial"><span style="color: black"><font size="2"><span style="font-size: 10pt; color: black; line-height: 115%"><img onload="ResizeImages(this) " alt="" style="width: 231px; height: 61px" src="http://mu.gate.vn/images/Editor/image/website/Su%20kien%20trong%20game/image084.jpg" /></span></font></span></span></p>
<p style="text-align: left">&nbsp;</p>
<p style="text-align: left"><span style="color: rgb(0,255,255)"><b><span style="font-size: 10pt">Qui định chiến thắng:</span></b></span></p>
<p style="text-align: left">&nbsp;&nbsp;</p>
<p>&nbsp;</p>
<div align="center">
  <center>
    <table class="MsoNormalTable" cellspacing="0" cellpadding="0" border="1" style="border-right: medium none; border-top: medium none; background: rgb(146,205,220); margin: auto auto auto 4.2pt; border-left: medium none; width: 491.3pt; border-bottom: medium none; border-collapse: collapse; -moz-background-clip: -moz-initial; -moz-background-origin: -moz-initial; -moz-background-inline-policy: -moz-initial">
      <tbody>
        <tr style="height: 11.25pt">
          <td width="88" style="border-right: windowtext 1pt solid; padding-right: 4.95pt; border-top: windowtext 1pt solid; padding-left: 4.95pt; padding-bottom: 0in; border-left: windowtext 1pt solid; width: 65.65pt; padding-top: 0in; border-bottom: windowtext 1pt solid; height: 11.25pt; background-color: transparent"><p class="MsoNormal" align="center" style="margin: 0in 4.5pt 10pt; text-align: center"><span style="font-family: Arial"><b><span style="font-size: 10pt; color: rgb(0,32,96); line-height: 115%">Chiến thắng</span></b></span><b><span style="font-size: 10pt; color: rgb(0,32,96); line-height: 115%; font-family: 'Verdana','sans-serif'">
            <o:p></o:p>
          </span></b></p></td>
          <td width="277" style="border-right: windowtext 1pt solid; padding-right: 4.95pt; border-top: windowtext 1pt solid; padding-left: 4.95pt; padding-bottom: 0in; border-left: rgb(236,233,216); width: 207.7pt; padding-top: 0in; border-bottom: windowtext 1pt solid; height: 11.25pt; background-color: transparent"><p class="MsoNormal" align="center" style="margin: 0in 0in 10pt; text-align: center"><span style="font-family: Arial"><b><span style="font-size: 10pt; color: rgb(0,32,96); line-height: 115%">Nội dung</span></b></span><b><span style="font-size: 10pt; color: rgb(0,32,96); line-height: 115%; font-family: 'Verdana','sans-serif'">
            <o:p></o:p>
          </span></b></p></td>
          <td width="108" style="border-right: windowtext 1pt solid; padding-right: 4.95pt; border-top: windowtext 1pt solid; padding-left: 4.95pt; padding-bottom: 0in; border-left: rgb(236,233,216); width: 81pt; padding-top: 0in; border-bottom: windowtext 1pt solid; height: 11.25pt; background-color: transparent"><p class="MsoNormal" align="center" style="margin: 0in 0in 10pt; text-align: center"><span style="font-family: Arial"><b><span style="font-size: 10pt; color: rgb(0,32,96); line-height: 115%">Giải thưởng</span></b></span><b><span style="font-size: 10pt; color: rgb(0,32,96); line-height: 115%; font-family: 'Verdana','sans-serif'">
            <o:p></o:p>
          </span></b></p></td>
          <td width="183" style="border-right: windowtext 1pt solid; padding-right: 4.95pt; border-top: windowtext 1pt solid; padding-left: 4.95pt; padding-bottom: 0in; border-left: rgb(236,233,216); width: 136.95pt; padding-top: 0in; border-bottom: windowtext 1pt solid; height: 11.25pt; background-color: transparent"><p class="MsoNormal" align="center" style="margin: 0in 0in 10pt; text-align: center"><span style="font-family: Arial"><b><span style="font-size: 10pt; color: rgb(0,32,96); line-height: 115%">Đối tượng</span></b></span><b><span style="font-size: 10pt; color: rgb(0,32,96); line-height: 115%; font-family: 'Verdana','sans-serif'">
            <o:p></o:p>
          </span></b></p></td>
        </tr>
        <tr style="height: 11.25pt">
          <td nowrap="nowrap" width="88" style="border-right: windowtext 1pt solid; padding-right: 4.95pt; border-top: rgb(236,233,216); padding-left: 4.95pt; padding-bottom: 0in; border-left: windowtext 1pt solid; width: 65.65pt; padding-top: 0in; border-bottom: windowtext 1pt solid; height: 11.25pt; background-color: transparent"><p class="MsoNormal" align="center" style="margin: 0in 0in 10pt; text-align: center"><span style="font-family: Arial"><span style="font-size: 10pt; color: rgb(0,32,96); line-height: 115%">Điều kiện 1</span></span><span style="font-size: 10pt; color: rgb(0,32,96); line-height: 115%; font-family: 'Verdana','sans-serif'">
            <o:p></o:p>
          </span></p></td>
          <td width="277" style="border-right: windowtext 1pt solid; padding-right: 4.95pt; border-top: rgb(236,233,216); padding-left: 4.95pt; padding-bottom: 0in; border-left: rgb(236,233,216); width: 207.7pt; padding-top: 0in; border-bottom: windowtext 1pt solid; height: 11.25pt; background-color: transparent"><p class="MsoNormal" align="center" style="margin: 0in 0in 10pt; text-align: center"><span style="font-family: Arial"><span style="font-size: 10pt; color: rgb(0,32,96); line-height: 115%">Gi&agrave;nh đ</span><span style="font-size: 10pt; color: rgb(0,32,96); line-height: 115%" lang="vi" xml:lang="vi">ược tr&ecirc;n 2 điểm trong thời gian được quy định v&agrave; c&oacute; điểm cao hơn</span></span><span style="font-size: 10pt; color: rgb(0,32,96); line-height: 115%; font-family: 'Verdana','sans-serif'">
            <o:p></o:p>
          </span></p></td>
          <td nowrap="nowrap" width="108" style="border-right: windowtext 1pt solid; padding-right: 4.95pt; border-top: rgb(236,233,216); padding-left: 4.95pt; padding-bottom: 0in; border-left: rgb(236,233,216); width: 81pt; padding-top: 0in; border-bottom: windowtext 1pt solid; height: 11.25pt; background-color: transparent"><p class="MsoNormal" align="center" style="margin: 0in 0in 10pt; text-align: center"><span style="font-family: Arial"><span style="font-size: 10pt; color: rgb(0,32,96); line-height: 115%">Ngọc hỗn nguy&ecirc;n 1</span></span><span style="font-size: 10pt; color: rgb(0,32,96); line-height: 115%; font-family: 'Verdana','sans-serif'">
            <o:p></o:p>
          </span></p></td>
          <td nowrap="nowrap" width="183" style="border-right: windowtext 1pt solid; padding-right: 4.95pt; border-top: rgb(236,233,216); padding-left: 4.95pt; padding-bottom: 0in; border-left: rgb(236,233,216); width: 136.95pt; padding-top: 0in; border-bottom: windowtext 1pt solid; height: 11.25pt; background-color: transparent"><p class="MsoNormal" align="center" style="margin: 0in 0in 10pt; text-align: center"><span style="font-family: Arial"><span style="font-size: 10pt; color: rgb(0,32,96); line-height: 115%">To&agrave;n bộ nh&oacute;m chiến thắng</span></span><span style="font-size: 10pt; color: rgb(0,32,96); line-height: 115%; font-family: 'Verdana','sans-serif'">
            <o:p></o:p>
          </span></p></td>
        </tr>
        <tr style="height: 11.25pt">
          <td nowrap="nowrap" width="88" style="border-right: windowtext 1pt solid; padding-right: 4.95pt; border-top: rgb(236,233,216); padding-left: 4.95pt; padding-bottom: 0in; border-left: windowtext 1pt solid; width: 65.65pt; padding-top: 0in; border-bottom: windowtext 1pt solid; height: 11.25pt; background-color: transparent"><p class="MsoNormal" align="center" style="margin: 0in 0in 10pt; text-align: center"><span style="font-family: Arial"><span style="font-size: 10pt; color: rgb(0,32,96); line-height: 115%">Điều kiện 2</span></span><span style="font-size: 10pt; color: rgb(0,32,96); line-height: 115%; font-family: 'Verdana','sans-serif'">
            <o:p></o:p>
          </span></p></td>
          <td nowrap="nowrap" width="277" style="border-right: windowtext 1pt solid; padding-right: 4.95pt; border-top: rgb(236,233,216); padding-left: 4.95pt; padding-bottom: 0in; border-left: rgb(236,233,216); width: 207.7pt; padding-top: 0in; border-bottom: windowtext 1pt solid; height: 11.25pt; background-color: transparent"><p class="MsoNormal" align="center" style="margin: 0in 0in 10pt; text-align: center"><span style="font-family: Arial"><span style="font-size: 10pt; color: rgb(0,32,96); line-height: 115%">Gi&agrave;nh đ</span><span style="font-size: 10pt; color: rgb(0,32,96); line-height: 115%" lang="vi" xml:lang="vi">ược 7 điểm trước nhất</span></span><span style="font-size: 10pt; color: rgb(0,32,96); line-height: 115%; font-family: 'Verdana','sans-serif'" lang="vi" xml:lang="vi">
            <o:p></o:p>
          </span></p></td>
          <td nowrap="nowrap" width="108" style="border-right: windowtext 1pt solid; padding-right: 4.95pt; border-top: rgb(236,233,216); padding-left: 4.95pt; padding-bottom: 0in; border-left: rgb(236,233,216); width: 81pt; padding-top: 0in; border-bottom: windowtext 1pt solid; height: 11.25pt; background-color: transparent"><p class="MsoNormal" align="center" style="margin: 0in 0in 10pt; text-align: center"><span style="font-family: Arial"><span style="font-size: 10pt; color: rgb(0,32,96); line-height: 115%">Ngọc hỗn nguy&ecirc;n 1</span></span><span style="font-size: 10pt; color: rgb(0,32,96); line-height: 115%; font-family: 'Verdana','sans-serif'">
            <o:p></o:p>
          </span></p></td>
          <td nowrap="nowrap" width="183" style="border-right: windowtext 1pt solid; padding-right: 4.95pt; border-top: rgb(236,233,216); padding-left: 4.95pt; padding-bottom: 0in; border-left: rgb(236,233,216); width: 136.95pt; padding-top: 0in; border-bottom: windowtext 1pt solid; height: 11.25pt; background-color: transparent"><p class="MsoNormal" align="center" style="margin: 0in 0in 10pt; text-align: center"><span style="font-family: Arial"><span style="font-size: 10pt; color: rgb(0,32,96); line-height: 115%">To&agrave;n bộ nh&oacute;m chiến thắng</span></span><span style="font-size: 10pt; color: rgb(0,32,96); line-height: 115%; font-family: 'Verdana','sans-serif'">
            <o:p></o:p>
          </span></p></td>
        </tr>
      </tbody>
    </table>
  </center>
</div>
<p></p>