<p><span style="color: #00ffff"><strong><span style="font-size: 10pt">C&aacute;ch v&agrave;o Chaos Castle</span></strong></span></p>
<p>&nbsp;</p>
<div align="center">
  <center>
  <table cellspacing="0" cellpadding="0" width="546" border="1" style="border-right: windowtext 1pt solid; border-top: windowtext 1pt solid; background: #92cddc; border-left: windowtext 1pt solid; width: 409.5pt; border-bottom: windowtext 1pt solid">
    <tbody>
      <tr>
        <td valign="top" width="70%" style="border-right: windowtext 1pt solid; padding-right: 0.75pt; border-top: windowtext 1pt solid; padding-left: 0.75pt; padding-bottom: 0in; border-left: windowtext 1pt solid; width: 70%; padding-top: 0.75pt; border-bottom: windowtext 1pt solid; background-color: transparent"><ul type="disc" style="margin-top: 0in">
          <li style="margin: 0in 0in 10pt; color: #002060; line-height: normal"><span style="font-size: 10pt">Gi&aacute;p Hộ Mệnh được b&aacute;n ở một số cửa hiệu trong c&aacute;c ng&ocirc;i l&agrave;ng. Được b&aacute;n bởi Kẻ b&aacute;n dạo ở ph&iacute;a Nam cổng Lorencia, Thợ thủ c&ocirc;ng ở Noria v&agrave; &ldquo;Wizard&rdquo; ở Devias.</span></li>
          <li style="margin: 0in 0in 10pt; color: #002060; line-height: normal"><span style="font-size: 10pt">Giống như &Aacute;o t&agrave;ng h&igrave;nh của L&acirc;u đ&agrave;i m&aacute;u, bạn c&oacute; thể nhấp chuột phải l&ecirc;n Gi&aacute;p Hộ Mệnh để kiểm tra thời gian c&oacute; thể bước v&agrave;o Chaos Castle.</span></li>
          <li style="margin: 0in 0in 10pt; color: #002060; line-height: normal"><span style="font-size: 10pt">Để bước v&agrave;o Chaos Castle, bạn nhấp chuột phải v&agrave;o Gi&aacute;p Hộ Mệnh (khi đ&uacute;ng thời gian y&ecirc;u cầu).</span></li>
          <li style="margin: 0in 0in 10pt; color: #002060; line-height: normal"><span style="font-size: 10pt">Nh&acirc;n vật của bạn sẽ được chuyển thẳng đến l&acirc;u đ&agrave;i c&oacute; cấp độ tương ứng v&agrave; bạn sẽ bị trừ 1 lượng chi ph&iacute; tương đương với cấp độ đ&oacute;.</span></li>
        </ul></td>
        <td valign="top" width="30%" style="border-right: windowtext 1pt solid; padding-right: 0.75pt; border-top: windowtext 1pt solid; padding-left: 0.75pt; padding-bottom: 0in; border-left: windowtext 1pt solid; width: 30%; padding-top: 0.75pt; border-bottom: windowtext 1pt solid; background-color: transparent"><div align="center">
          <table cellpadding="0" width="100%" border="0" style="width: 100%">
            <tbody>
              <tr>
                <td style="border-right: #ffffff; padding-right: 0.75pt; border-top: #ffffff; padding-left: 0.75pt; padding-bottom: 0in; border-left: #ffffff; padding-top: 0.75pt; border-bottom: #ffffff; background-color: transparent"><div style="margin: 0in 0in 0pt; line-height: normal" align="center"><span style="font-size: 10pt; color: #002060">Gi&aacute;p Hộ Mệnh<br>
                  (Armor of Guardsman)</span></div></td>
              </tr>
            </tbody>
          </table>
          </center>
        </div>
            <p style="text-align: center"><img onload="ResizeImages(this) " height="78" alt="" width="81" src="http://mu.gate.vn/images/Editor/image/website/Su%20kien%20trong%20game/image034.jpg"></p></td>
      </tr>
      <tr>
        <td valign="top" colspan="2" style="border-right: windowtext 1pt solid; padding-right: 0.75pt; border-top: windowtext 1pt solid; padding-left: 0.75pt; padding-bottom: 0in; border-left: windowtext 1pt solid; padding-top: 0.75pt; border-bottom: windowtext 1pt solid; background-color: transparent"><div align="center">
          <center>
          <table cellspacing="1" cellpadding="0" width="540" border="0" style="background: #92cddc; width: 405pt">
            <tbody>
              <tr style="height: 14.25pt">
                <td width="166" style="border-right: #ffffff; padding-right: 2.25pt; border-top: #ffffff; padding-left: 2.25pt; background: none transparent scroll repeat 0% 0%; padding-bottom: 0in; border-left: #ffffff; width: 124.5pt; padding-top: 2.25pt; border-bottom: #ffffff; height: 14.25pt"><div style="margin: 0in 0in 0pt; line-height: normal" align="center"><span style="font-size: 10pt; color: #002060">Chaos Castle tầng thứ</span></div></td>
                <td width="200" style="border-right: #ffffff; padding-right: 2.25pt; border-top: #ffffff; padding-left: 2.25pt; background: none transparent scroll repeat 0% 0%; padding-bottom: 0in; border-left: #ffffff; width: 150pt; padding-top: 2.25pt; border-bottom: #ffffff; height: 14.25pt"><div style="margin: 0in 0in 0pt; line-height: normal" align="center"><span style="font-size: 10pt; color: #002060">Cấp độ của nh&acirc;n vật b&igrave;nh thường</span></div></td>
                <td width="250" style="border-right: #ffffff; padding-right: 2.25pt; border-top: #ffffff; padding-left: 2.25pt; background: none transparent scroll repeat 0% 0%; padding-bottom: 0in; border-left: #ffffff; width: 187.5pt; padding-top: 2.25pt; border-bottom: #ffffff; height: 14.25pt"><div style="margin: 0in 0in 0pt; line-height: normal" align="center"><span style="font-size: 10pt; color: #002060">Cấp độ của Đấu Sĩ v&agrave; Ch&uacute;a Tể</span></div></td>
                <td width="120" style="border-right: #ffffff; padding-right: 2.25pt; border-top: #ffffff; padding-left: 2.25pt; background: none transparent scroll repeat 0% 0%; padding-bottom: 0in; border-left: #ffffff; width: 1.25in; padding-top: 2.25pt; border-bottom: #ffffff; height: 14.25pt"><div style="margin: 0in 0in 0pt; line-height: normal" align="center"><span style="font-size: 10pt; color: #002060">Chi ph&iacute;</span></div></td>
              </tr>
              <tr style="height: 15pt">
                <td style="border-right: #ffffff; padding-right: 2.25pt; border-top: #ffffff; padding-left: 2.25pt; background: none transparent scroll repeat 0% 0%; padding-bottom: 0in; border-left: #ffffff; padding-top: 2.25pt; border-bottom: #ffffff; height: 15pt"><div style="margin: 0in 0in 0pt; line-height: normal" align="center"><span style="font-size: 10pt; color: #002060">1</span></div></td>
                <td style="border-right: #ffffff; padding-right: 2.25pt; border-top: #ffffff; padding-left: 2.25pt; background: none transparent scroll repeat 0% 0%; padding-bottom: 0in; border-left: #ffffff; padding-top: 2.25pt; border-bottom: #ffffff; height: 15pt"><div style="margin: 0in 0in 0pt; line-height: normal" align="center"><span style="font-size: 10pt; color: #002060">15~49</span></div></td>
                <td style="border-right: #ffffff; padding-right: 2.25pt; border-top: #ffffff; padding-left: 2.25pt; background: none transparent scroll repeat 0% 0%; padding-bottom: 0in; border-left: #ffffff; padding-top: 2.25pt; border-bottom: #ffffff; height: 15pt"><div style="margin: 0in 0in 0pt; line-height: normal" align="center"><span style="font-size: 10pt; color: #002060">15~29</span></div></td>
                <td style="border-right: #ffffff; padding-right: 2.25pt; border-top: #ffffff; padding-left: 2.25pt; background: none transparent scroll repeat 0% 0%; padding-bottom: 0in; border-left: #ffffff; padding-top: 2.25pt; border-bottom: #ffffff; height: 15pt"><div style="margin: 0in 0in 0pt; line-height: normal" align="center"><span style="font-size: 10pt; color: #002060">25,000z</span></div></td>
              </tr>
              <tr style="height: 13.5pt">
                <td style="border-right: #ffffff; padding-right: 2.25pt; border-top: #ffffff; padding-left: 2.25pt; background: none transparent scroll repeat 0% 0%; padding-bottom: 0in; border-left: #ffffff; padding-top: 2.25pt; border-bottom: #ffffff; height: 13.5pt"><div style="margin: 0in 0in 0pt; line-height: normal" align="center"><span style="font-size: 10pt; color: #002060">2</span></div></td>
                <td style="border-right: #ffffff; padding-right: 2.25pt; border-top: #ffffff; padding-left: 2.25pt; background: none transparent scroll repeat 0% 0%; padding-bottom: 0in; border-left: #ffffff; padding-top: 2.25pt; border-bottom: #ffffff; height: 13.5pt"><div style="margin: 0in 0in 0pt; line-height: normal" align="center"><span style="font-size: 10pt; color: #002060">50~119</span></div></td>
                <td style="border-right: #ffffff; padding-right: 2.25pt; border-top: #ffffff; padding-left: 2.25pt; background: none transparent scroll repeat 0% 0%; padding-bottom: 0in; border-left: #ffffff; padding-top: 2.25pt; border-bottom: #ffffff; height: 13.5pt"><div style="margin: 0in 0in 0pt; line-height: normal" align="center"><span style="font-size: 10pt; color: #002060">30~99</span></div></td>
                <td style="border-right: #ffffff; padding-right: 2.25pt; border-top: #ffffff; padding-left: 2.25pt; background: none transparent scroll repeat 0% 0%; padding-bottom: 0in; border-left: #ffffff; padding-top: 2.25pt; border-bottom: #ffffff; height: 13.5pt"><div style="margin: 0in 0in 0pt; line-height: normal" align="center"><span style="font-size: 10pt; color: #002060">80,000z</span></div></td>
              </tr>
              <tr style="height: 15pt">
                <td style="border-right: #ffffff; padding-right: 2.25pt; border-top: #ffffff; padding-left: 2.25pt; background: none transparent scroll repeat 0% 0%; padding-bottom: 0in; border-left: #ffffff; padding-top: 2.25pt; border-bottom: #ffffff; height: 15pt"><div style="margin: 0in 0in 0pt; line-height: normal" align="center"><span style="font-size: 10pt; color: #002060">3</span></div></td>
                <td style="border-right: #ffffff; padding-right: 2.25pt; border-top: #ffffff; padding-left: 2.25pt; background: none transparent scroll repeat 0% 0%; padding-bottom: 0in; border-left: #ffffff; padding-top: 2.25pt; border-bottom: #ffffff; height: 15pt"><div style="margin: 0in 0in 0pt; line-height: normal" align="center"><span style="font-size: 10pt; color: #002060">120~179</span></div></td>
                <td style="border-right: #ffffff; padding-right: 2.25pt; border-top: #ffffff; padding-left: 2.25pt; background: none transparent scroll repeat 0% 0%; padding-bottom: 0in; border-left: #ffffff; padding-top: 2.25pt; border-bottom: #ffffff; height: 15pt"><div style="margin: 0in 0in 0pt; line-height: normal" align="center"><span style="font-size: 10pt; color: #002060">100~159</span></div></td>
                <td style="border-right: #ffffff; padding-right: 2.25pt; border-top: #ffffff; padding-left: 2.25pt; background: none transparent scroll repeat 0% 0%; padding-bottom: 0in; border-left: #ffffff; padding-top: 2.25pt; border-bottom: #ffffff; height: 15pt"><div style="margin: 0in 0in 0pt; line-height: normal" align="center"><span style="font-size: 10pt; color: #002060">150,000z</span></div></td>
              </tr>
              <tr style="height: 13.5pt">
                <td style="border-right: #ffffff; padding-right: 2.25pt; border-top: #ffffff; padding-left: 2.25pt; background: none transparent scroll repeat 0% 0%; padding-bottom: 0in; border-left: #ffffff; padding-top: 2.25pt; border-bottom: #ffffff; height: 13.5pt"><div style="margin: 0in 0in 0pt; line-height: normal" align="center"><span style="font-size: 10pt; color: #002060">4</span></div></td>
                <td style="border-right: #ffffff; padding-right: 2.25pt; border-top: #ffffff; padding-left: 2.25pt; background: none transparent scroll repeat 0% 0%; padding-bottom: 0in; border-left: #ffffff; padding-top: 2.25pt; border-bottom: #ffffff; height: 13.5pt"><div style="margin: 0in 0in 0pt; line-height: normal" align="center"><span style="font-size: 10pt; color: #002060">180~239</span></div></td>
                <td style="border-right: #ffffff; padding-right: 2.25pt; border-top: #ffffff; padding-left: 2.25pt; background: none transparent scroll repeat 0% 0%; padding-bottom: 0in; border-left: #ffffff; padding-top: 2.25pt; border-bottom: #ffffff; height: 13.5pt"><div style="margin: 0in 0in 0pt; line-height: normal" align="center"><span style="font-size: 10pt; color: #002060">160~219</span></div></td>
                <td style="border-right: #ffffff; padding-right: 2.25pt; border-top: #ffffff; padding-left: 2.25pt; background: none transparent scroll repeat 0% 0%; padding-bottom: 0in; border-left: #ffffff; padding-top: 2.25pt; border-bottom: #ffffff; height: 13.5pt"><div style="margin: 0in 0in 0pt; line-height: normal" align="center"><span style="font-size: 10pt; color: #002060">250,000z</span></div></td>
              </tr>
              <tr style="height: 15pt">
                <td style="border-right: #ffffff; padding-right: 2.25pt; border-top: #ffffff; padding-left: 2.25pt; background: none transparent scroll repeat 0% 0%; padding-bottom: 0in; border-left: #ffffff; padding-top: 2.25pt; border-bottom: #ffffff; height: 15pt"><div style="margin: 0in 0in 0pt; line-height: normal" align="center"><span style="font-size: 10pt; color: #002060">5</span></div></td>
                <td style="border-right: #ffffff; padding-right: 2.25pt; border-top: #ffffff; padding-left: 2.25pt; background: none transparent scroll repeat 0% 0%; padding-bottom: 0in; border-left: #ffffff; padding-top: 2.25pt; border-bottom: #ffffff; height: 15pt"><div style="margin: 0in 0in 0pt; line-height: normal" align="center"><span style="font-size: 10pt; color: #002060">240~299</span></div></td>
                <td style="border-right: #ffffff; padding-right: 2.25pt; border-top: #ffffff; padding-left: 2.25pt; background: none transparent scroll repeat 0% 0%; padding-bottom: 0in; border-left: #ffffff; padding-top: 2.25pt; border-bottom: #ffffff; height: 15pt"><div style="margin: 0in 0in 0pt; line-height: normal" align="center"><span style="font-size: 10pt; color: #002060">220~279</span></div></td>
                <td style="border-right: #ffffff; padding-right: 2.25pt; border-top: #ffffff; padding-left: 2.25pt; background: none transparent scroll repeat 0% 0%; padding-bottom: 0in; border-left: #ffffff; padding-top: 2.25pt; border-bottom: #ffffff; height: 15pt"><div style="margin: 0in 0in 0pt; line-height: normal" align="center"><span style="font-size: 10pt; color: #002060">400,000z</span></div></td>
              </tr>
              <tr style="height: 17.25pt">
                <td style="border-right: #ffffff; padding-right: 2.25pt; border-top: #ffffff; padding-left: 2.25pt; background: none transparent scroll repeat 0% 0%; padding-bottom: 0in; border-left: #ffffff; padding-top: 2.25pt; border-bottom: #ffffff; height: 17.25pt"><div style="margin: 0in 0in 6pt; line-height: normal" align="center"><span style="font-size: 10pt; color: #002060">6</span></div>
                      <div style="margin: 0in 0in 6pt; line-height: normal" align="center"><span style="font-size: 10pt; color: #002060">7</span></div></td>
                <td style="border-right: #ffffff; padding-right: 2.25pt; border-top: #ffffff; padding-left: 2.25pt; background: none transparent scroll repeat 0% 0%; padding-bottom: 0in; border-left: #ffffff; padding-top: 2.25pt; border-bottom: #ffffff; height: 17.25pt"><div style="margin: 0in 0in 6pt; line-height: normal" align="center"><span style="font-size: 10pt; color: #002060">300~400</span></div></td>
                <td style="border-right: #ffffff; padding-right: 2.25pt; border-top: #ffffff; padding-left: 2.25pt; background: none transparent scroll repeat 0% 0%; padding-bottom: 0in; border-left: #ffffff; padding-top: 2.25pt; border-bottom: #ffffff; height: 17.25pt"><div style="margin: 0in 0in 6pt; line-height: normal" align="center"><span style="font-size: 10pt; color: #002060">280~400</span></div></td>
                <td style="border-right: #ffffff; padding-right: 2.25pt; border-top: #ffffff; padding-left: 2.25pt; background: none transparent scroll repeat 0% 0%; padding-bottom: 0in; border-left: #ffffff; padding-top: 2.25pt; border-bottom: #ffffff; height: 17.25pt"><div style="margin: 0in 0in 6pt; line-height: normal" align="center"><span style="font-size: 10pt; color: #002060">650,000z</span></div></td>
              </tr>
            </tbody>
          </table>
        </div></td>
      </tr>
    </tbody>
  </table>
  </center>
  <p>&nbsp;</p>
  <p><img onload="ResizeImages(this) " height="300" alt="" width="524" src="http://mu.gate.vn/images/Editor/image/website/Su%20kien%20trong%20game/image035.jpg"></p>
  <p><img onload="ResizeImages(this) " height="294" alt="" width="473" src="http://mu.gate.vn/images/Editor/image/website/Su%20kien%20trong%20game/image036.jpg"></p>
  <p>&nbsp;</p>
  <p style="text-align: left"><span style="color: #00ffff"><strong><span style="font-size: 10pt">Chaos Castle</span></strong></span></p>
  <p style="text-align: left">&nbsp;</p>
</div>
<div style="margin: 0in 0in 10pt 0.5in; text-indent: -0.25in; line-height: normal; text-align: justify"><span style="color: #99ccff"><span style="font-size: 9pt">-<span style="font: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span>&nbsp;<span style="font-size: 10pt">Tổng số người c&oacute; thể tham gia v&agrave;o Chaos Castle l&agrave; 100 v&agrave; dựa theo quy tắc sau: </span></span></div>
<div style="margin: 0in 0in 10pt 0.5in; text-align: justify"><span style="color: #99ccff"><span style="font-size: 10pt; line-height: 115%">o&nbsp;Số lượng người chơi tối đa l&agrave; 70</span></span></div>
<div style="margin: 0in 0in 10pt 0.5in; text-align: justify"><span style="color: #99ccff"><span style="font-size: 10pt; line-height: 115%">o&nbsp;Số lượng qu&aacute;i vật tối thiểu l&agrave; 30</span>&nbsp;</span></div>
<div style="margin: 0in 0in 0pt 0.5in; text-indent: -0.25in; line-height: normal; text-align: justify"><span style="color: #99ccff"><span style="font-size: 9pt">-<span style="font: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><span style="font-size: 10pt">Nếu số lượng người chơi &iacute;t hơn 70 th&igrave; số lượng qu&aacute;i vật sẽ được tự động tăng th&ecirc;m cho đủ số 100.</span></span></div>
<div style="margin: 0in 0in 0pt 0.5in; line-height: normal; text-align: justify"><span style="color: #99ccff">&nbsp;</span></div>
<div style="margin: 0in 0in 0pt 0.5in; text-indent: -0.25in; line-height: normal; text-align: justify"><span style="color: #99ccff"><span style="font-size: 9pt">-<span style="font: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><span style="font-size: 10pt">Sự kiện chỉ diễn ra khi c&oacute; &iacute;t nhất 2 người chơi c&ugrave;ng v&agrave;o 1 l&acirc;u đ&agrave;i. Nếu chỉ c&oacute; 1 người v&agrave;o l&acirc;u đ&agrave;i, chi ph&iacute; v&agrave;o cổng sẽ được ho&agrave;n trả v&agrave; người đ&oacute; buộc phải rời khỏi l&acirc;u đ&agrave;i.</span></span></div>
<div style="margin: 0in 0in 0pt 0.5in; text-align: justify"><span style="color: #99ccff">&nbsp;</span></div>
<div style="margin: 0in 0in 0pt 0.5in; text-indent: -0.25in; line-height: normal; text-align: justify"><span style="color: #99ccff"><span style="font-size: 9pt">-<span style="font: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><span style="font-size: 10pt">Khi người chơi bước v&agrave;o Chaos Castle, h&igrave;nh d&aacute;ng của anh ta sẽ được thay đổi như một binh l&iacute;nh.</span></span></div>
<div style="margin: 0in 0in 0pt 0.5in; text-align: justify"><span style="color: #99ccff">&nbsp;</span></div>
<div style="margin: 0in 0in 10pt 0.5in; text-indent: -0.25in; line-height: normal; text-align: justify"><span style="color: #99ccff"><span style="font-size: 9pt">-<span style="font: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><span style="font-size: 10pt">Chỉ c&oacute; h&igrave;nh d&aacute;ng bị thay đổi, c&aacute;c chỉ số thực sẽ kh&ocirc;ng bị thay đổi.</span></span></div>
<center>
  <table height="200" cellspacing="1" cellpadding="1" width="200" align="center" border="0">
    <tbody>
      <tr>
        <td><img onload="ResizeImages(this) " height="215" alt="" width="249" src="http://mu.gate.vn/images/Editor/image/website/Su%20kien%20trong%20game/image037.jpg"></td>
        <td><img onload="ResizeImages(this) " height="215" alt="" width="211" src="http://mu.gate.vn/images/Editor/image/website/Su%20kien%20trong%20game/image038.jpg"></td>
      </tr>
    </tbody>
  </table>
</center>
<div style="margin: 0in 0in 10pt 0.5in; text-indent: -0.25in; line-height: normal; text-align: justify">&nbsp;</div>
<div style="margin: 0in 0in 10pt 0.5in; text-indent: -0.25in; line-height: normal; text-align: justify"><span style="color: #99ccff"><span style="font-size: 9pt">-<span style="font: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><span style="font-size: 10pt">Để c&oacute; thể ph&acirc;n biệt c&aacute;c Class của nh&acirc;n vật, mỗi Class sẽ c&oacute; Kiếm, Gậy v&agrave; Cung tuỳ theo Class của nhận vật đ&oacute;.</span></span></div>
<div style="margin: 0in 0in 10pt 0.5in; text-indent: -0.25in; line-height: normal; text-align: justify">&nbsp;</div>
<div style="margin: 0in 0in 10pt 0.5in; text-indent: -0.25in; line-height: normal; text-align: center"><span style="color: #99ccff"><span style="font-size: 10pt"><img onload="ResizeImages(this) " height="304" alt="" width="521" src="http://mu.gate.vn/images/Editor/image/website/Su%20kien%20trong%20game/image039.jpg"></span></span></div>
<div style="margin: 0in 0in 10pt; line-height: normal; text-align: justify">&nbsp;</div>
<div style="margin: 0in 0in 10pt; line-height: normal; text-align: justify"><span style="color: #00ffff"><span><span><b><span style="font-size: 10pt">Những điều luật cơ bản</span></b></span></span></span></div>
<div style="margin: 0in 0in 0pt 0.5in; text-indent: -0.25in; line-height: normal; text-align: justify"><span style="color: #99ccff"><span style="font-size: 9pt">-<span style="font: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><span style="font-size: 10pt">Nếu số lượng người chơi &iacute;t hơn 70 th&igrave; số lượng qu&aacute;i vật sẽ được tự động tăng th&ecirc;m cho đủ số 100.</span></span></div>
<div style="margin: 0in 0in 0pt 0.5in; line-height: normal; text-align: justify"><span style="color: #99ccff">&nbsp;</span></div>
<div style="margin: 0in 0in 0pt 0.5in; text-indent: -0.25in; line-height: normal; text-align: justify"><span style="color: #99ccff"><span style="font-size: 9pt">-<span style="font: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><span style="font-size: 10pt">Tất cả c&aacute;c nh&acirc;n vật tham gia v&agrave;o Chaos Castle đều l&agrave; đối thủ của nhau, v&igrave; vậy bạn kh&ocirc;ng cần phải chuyển sang chế độ PVP.</span></span></div>
<div style="margin: 0in 0in 0pt 0.5in; text-align: justify"><span style="color: #99ccff">&nbsp;</span></div>
<div style="margin: 0in 0in 0pt 0.5in; text-indent: -0.25in; line-height: normal; text-align: justify"><span style="color: #99ccff"><span style="font-size: 9pt">-<span style="font: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><span style="font-size: 10pt">H&atilde;y nhớ rằng: c&aacute;c bạn chỉ c&oacute; thể tấn c&ocirc;ng lẫn nhau khi c&aacute;c bạn bước v&agrave;o b&ecirc;n trong l&acirc;u đ&agrave;i.</span></span></div>
<div style="margin: 0in 0in 0pt 0.5in; text-align: justify"><span style="color: #99ccff">&nbsp;</span></div>
<div style="margin: 0in 0in 0pt 0.5in; text-indent: -0.25in; line-height: normal; text-align: justify"><span style="color: #99ccff"><span style="font-size: 9pt">-<span style="font: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><span style="font-size: 10pt">Một khi bạn bước v&agrave;o Chaos Castle, bạn sẽ kh&ocirc;ng thể th&agrave;nh lập đội, nh&oacute;m.</span></span></div>
<div style="margin: 0in 0in 0pt 0.5in; text-align: justify"><span style="color: #99ccff">&nbsp;</span></div>
<div style="margin: 0in 0in 0pt 0.5in; text-indent: -0.25in; line-height: normal; text-align: justify"><span style="color: #99ccff"><span style="font-size: 9pt">-<span style="font: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><span style="font-size: 10pt">V&agrave; khi v&agrave;o trong l&acirc;u đ&agrave;i, bạn sẽ kh&ocirc;ng thể mở cửa h&agrave;ng c&aacute; nh&acirc;n cũng như kh&ocirc;ng thể th&aacute;ch đấu lẫn nhau.</span></span></div>
<div style="margin: 0in 0in 0pt 0.5in; text-align: justify"><span style="color: #99ccff">&nbsp;</span></div>
<div style="margin: 0in 0in 0pt 0.5in; text-indent: -0.25in; line-height: normal; text-align: justify"><span style="color: #99ccff"><span style="font-size: 9pt">-<span style="font: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><span style="font-size: 10pt">Bước v&agrave;o Chaos Castle đồng nghĩa với việc bạn kh&ocirc;ng thể tr&ograve; chuyện với người kh&aacute;c nữa.</span></span></div>
<div style="margin: 0in 0in 0pt 0.5in; text-align: justify"><span style="color: #99ccff">&nbsp;</span></div>
<div style="margin: 0in 0in 0pt 0.5in; text-indent: -0.25in; line-height: normal; text-align: justify"><span style="color: #99ccff"><span style="font-size: 9pt">-<span style="font: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><span style="font-size: 10pt">Bạn kh&ocirc;ng thể th&agrave;nh lập đội nh&oacute;m hay b&agrave;n luận trong Chaos Castle.</span></span></div>
<div style="margin: 0in 0in 0pt 0.5in; text-align: justify"><span style="color: #99ccff">&nbsp;</span></div>
<div style="margin: 0in 0in 0pt 0.5in; text-indent: -0.25in; line-height: normal; text-align: justify"><span style="color: #99ccff"><span style="font-size: 9pt">-<span style="font: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><span style="font-size: 10pt">Khi đ&atilde; ở trong l&acirc;u đ&agrave;i, Ti&ecirc;n Nữ thuộc d&ograve;ng Hỗ trợ chỉ c&oacute; thể tự Hỗ trợ cho bản th&acirc;n m&igrave;nh m&agrave; th&ocirc;i.</span></span></div>
<div style="margin: 0in 0in 0pt 0.5in; text-align: justify"><span style="color: #99ccff">&nbsp;</span></div>
<div style="margin: 0in 0in 0pt 0.5in; text-indent: -0.25in; line-height: normal; text-align: justify"><span style="color: #99ccff"><span style="font-size: 9pt">-<span style="font: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><span style="font-size: 10pt">Khi c&aacute;c người chơi đ&atilde; ở trong Chaos Castle, sức tấn c&ocirc;ng của họ sẽ bị giảm đi 50%.</span></span></div>
<div style="margin: 0in 0in 0pt 0.5in; text-align: justify"><span style="color: #99ccff">&nbsp;</span></div>
<div style="margin: 0in 0in 0pt 0.5in; text-indent: -0.25in; line-height: normal; text-align: justify"><span style="color: #99ccff"><span style="font-size: 9pt">-<span style="font: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><span style="font-size: 10pt">Người chơi sẽ kh&ocirc;ng sợ nhầm lẫn giữa nh&acirc;n vật của m&igrave;nh v&agrave; của người kh&aacute;c v&igrave; họ sẽ được bổ sung những hiệu ứng ri&ecirc;ng.</span></span></div>
<div style="margin: 0in 0in 0pt 0.5in; text-align: justify"><span style="color: #99ccff">&nbsp;</span></div>
<div style="margin: 0in 0in 0pt 0.5in; text-indent: -0.25in; line-height: normal; text-align: justify"><span style="color: #99ccff"><span style="font-size: 9pt">-<span style="font: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><span style="font-size: 10pt">Điểm thưởng: khi bạn hạ 1 người chơi, bạn được thưởng 1 điểm v&agrave; điểm thưởng sẽ gấp đ&ocirc;i (2) khi bạn hạ 1 qu&aacute;i vật.</span></span></div>
<div style="margin: 0in 0in 0pt 0.5in; text-align: justify"><span style="color: #99ccff">&nbsp;</span></div>
<div style="margin: 0in 0in 0pt 0.5in; text-indent: -0.25in; line-height: normal; text-align: justify"><span style="color: #99ccff"><span style="font-size: 9pt">-<span style="font: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><span style="font-size: 10pt">Sau khi đ&atilde; hạ hết số qu&aacute;i vật v&agrave; chỉ c&ograve;n 2 người chơi sống s&oacute;t, người n&agrave;o c&oacute; số điểm thưởng cao hơn sẽ l&agrave; người chiến thắng.</span></span></div>
<div style="margin: 0in 0in 0pt 0.5in; text-align: justify"><span style="color: #99ccff">&nbsp;</span></div>
<div style="margin: 0in 0in 0pt 0.5in; text-indent: -0.25in; line-height: normal; text-align: justify"><span style="color: #99ccff"><span style="font-size: 9pt">-<span style="font: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><span style="font-size: 10pt">Bản đồ của Chaos Castle sẽ thu nhỏ lại dần, tỉ lệ thu nhỏ sẽ t&ugrave;y thuộc v&agrave;o số lượng người chơi c&ograve;n sống s&oacute;t (kể cả qu&aacute;i vật).</span></span></div>
<div style="margin: 0in 0in 0pt 0.5in; line-height: normal; text-align: justify"><span style="color: #99ccff"><span style="font-size: 10pt"><br>
  o Giai đoạn 1 (tổng số người chơi c&ograve;n lại l&agrave; 40)</span></span></div>
<div style="margin: 0in 0in 0pt 0.5in; line-height: normal; text-align: justify"><span style="color: #99ccff">&nbsp;</span></div>
<div style="margin: 0in 0in 0pt 0.5in; line-height: normal; text-align: justify"><span style="color: #99ccff"><span style="font-size: 10pt">o Giai đoạn 2 (tổng số người chơi c&ograve;n lại l&agrave; 30)</span></span></div>
<div style="margin: 0in 0in 0pt 0.5in; line-height: normal; text-align: justify"><span style="color: #99ccff"><span style="font-size: 10pt"><br>
  o Giai đoạn 3 (tổng số người chơi c&ograve;n lại l&agrave; 20)</span></span></div>
<div style="margin: 0in 0in 0pt 0.5in; line-height: normal; text-align: justify"><span style="color: #99ccff">&nbsp;</span></div>
<div style="margin: 0in 0in 10pt 0.5in; text-indent: -0.25in; line-height: normal; text-align: justify"><span style="color: #99ccff"><span style="font-size: 9pt">-<span style="font: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><span style="font-size: 10pt">Người chơi bị hạ sẽ được hồi sinh tại Devias.</span></span></div>
<div style="margin: 0in 0in 10pt; line-height: normal; text-align: justify"><span style="color: #00ffff"><span><b><span style="font-size: 10pt">Qu&aacute;i vật (Monsters)</span></b></span></span></div>
<div style="margin: 0in 0in 0pt 0.5in; text-indent: -0.25in; line-height: normal; text-align: justify"><span style="color: #99ccff"><span style="font-size: 9pt">-<span style="font: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><span style="font-size: 10pt">H&igrave;nh dạng của qu&aacute;i vật sẽ tương tự như h&igrave;nh dạng của người chơi.</span></span></div>
<div style="margin: 0in 0in 0pt 0.5in; line-height: normal; text-align: justify"><span style="color: #99ccff">&nbsp;</span></div>
<div style="margin: 0in 0in 0pt 0.5in; text-indent: -0.25in; line-height: normal; text-align: justify"><span style="color: #99ccff"><span style="font-size: 9pt">-<span style="font: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><span style="font-size: 10pt">Số lượng qu&aacute;i vật sẽ thay đổi tuỳ thuộc v&agrave;o số lượng người tham gia v&agrave;o Chaos Castle (tối thiểu l&agrave; 30 v&agrave; tối đa l&agrave; 98).</span></span></div>
<div style="margin: 0in 0in 0pt 0.5in; text-align: justify"><span style="color: #99ccff">&nbsp;</span></div>
<div style="margin: 0in 0in 10pt 0.5in; text-indent: -0.25in; line-height: normal; text-align: justify"><span style="color: #99ccff"><span style="font-size: 9pt">-<span style="font: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><span style="font-size: 10pt">Khi qu&aacute;i vật bị ti&ecirc;u diệt, n&oacute; sẽ nổ tung v&agrave; l&agrave;m cho người chơi bị hất văng ra ph&iacute;a sau, k&egrave;m theo đ&oacute;, người chơi sẽ mất 1 lượng m&aacute;u kh&ocirc;ng đ&aacute;ng kể.</span></span></div>
<div style="margin: 0in 0in 10pt; line-height: normal; text-align: justify"><span style="color: #00ffff"><span><b><span style="font-size: 10pt">Người chơi sẽ thua cuộc khi:</span></b></span></span></div>
<div style="margin: 0in 0in 0pt 0.5in; text-indent: -0.25in; line-height: normal; text-align: justify"><span style="color: #99ccff"><span style="font-size: 9pt">-<span style="font: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><span style="font-size: 10pt">Nếu họ bị tấn c&ocirc;ng v&agrave; lượng HP của họ giảm về &ldquo;0&rdquo;.</span></span></div>
<div style="margin: 0in 0in 0pt 0.5in; line-height: normal; text-align: justify"><span style="color: #99ccff">&nbsp;</span></div>
<div style="margin: 0in 0in 0pt 0.5in; text-indent: -0.25in; line-height: normal; text-align: justify"><span style="color: #99ccff"><span style="font-size: 9pt">-<span style="font: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><span style="font-size: 10pt">Khi họ- K bị đ&aacute;nh bật ra khỏi l&acirc;u đ&agrave;i.</span></span></div>
<div style="margin: 0in 0in 0pt 0.5in; line-height: normal; text-align: justify"><span style="color: #99ccff">&nbsp;</span></div>
<div style="margin: 0in 0in 0pt 0.5in; text-indent: -0.25in; line-height: normal; text-align: justify"><span style="color: #99ccff"><span style="font-size: 9pt">-<span style="font: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><span style="font-size: 10pt">Khi họ bị kẹp trong bẫy v&agrave; lượng HP của họ giảm về &ldquo;0&rdquo;.</span></span></div>
<div style="margin: 0in 0in 10pt 0.5in; text-align: justify"><span style="color: #99ccff">&nbsp;</span></div>
<div style="margin: 0in 0in 10pt; line-height: normal; text-align: justify"><span style="color: #00ffff"><span><b><span style="font-size: 10pt">Khi n&agrave;o th&igrave; sự kiện kết th&uacute;c?</span></b></span></span></div>
<div style="margin: 0in 0in 0pt 0.5in; text-indent: -0.25in; line-height: normal; text-align: justify"><span style="color: #99ccff"><span style="font-size: 9pt">-<span style="font: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><span style="font-size: 10pt">Sự kiện sẽ kết th&uacute;c khi mọi người chơi đều bị hạ.</span></span></div>
<div style="margin: 0in 0in 0pt 0.5in; line-height: normal; text-align: justify"><span style="color: #99ccff">&nbsp;</span></div>
<div style="margin: 0in 0in 0pt 0.5in; text-indent: -0.25in; line-height: normal; text-align: justify"><span style="color: #99ccff"><span style="font-size: 9pt">-<span style="font: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><span style="font-size: 10pt">Khi tất cả qu&aacute;i vật đều bị ti&ecirc;u diệt v&agrave; chỉ c&ograve;n 1 người chơi s&oacute;ng s&oacute;t (trong thời gian cho ph&eacute;p).</span></span></div>
<div style="margin: 0in 0in 0pt 0.5in; text-align: justify"><span style="color: #99ccff">&nbsp;</span></div>
<div style="margin: 0in 0in 10pt 0.5in; text-indent: -0.25in; line-height: normal; text-align: justify"><span style="color: #99ccff"><span style="font-size: 9pt">-<span style="font: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><span style="font-size: 10pt">Khi c&ograve;n 2 người chơi sống s&oacute;t (trong thời gian cho ph&eacute;p), người n&agrave;o c&oacute; số điểm thưởng cao hơn sẽ l&agrave; người chiến thắng.</span></span></div>
<div style="margin: 0in 0in 10pt; line-height: normal; text-align: justify"><span style="color: #00ffff"><span><b><span style="font-size: 10pt">Cạm bẫy (Traps)</span></b></span></span></div>
<div style="margin: 0in 0in 0pt 0.5in; text-indent: -0.25in; line-height: normal; text-align: justify"><span style="color: #99ccff"><span style="font-size: 9pt">-<span style="font: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><span style="font-size: 10pt">Những chiếc bẫy sẽ được giảm dần khi số lượng của người chơi v&agrave; qu&aacute;i vật nhỏ hơn 50.</span></span></div>
<div style="margin: 0in 0in 0pt 0.5in; line-height: normal; text-align: justify"><span style="color: #99ccff">&nbsp;</span></div>
<div style="margin: 0in 0in 10pt 0.5in; text-indent: -0.25in; line-height: normal; text-align: justify"><span style="color: #99ccff"><span style="font-size: 9pt">-<span style="font: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><span style="font-size: 10pt">Những c&aacute;i bẫy sẽ g&acirc;y chấn thương cho nh&acirc;n vật cho d&ugrave; họ c&oacute; chống đỡ hay kh&ocirc;ng.</span></span></div>
<div style="margin: 0in 0in 10pt; line-height: normal; text-align: justify"><span style="color: #00ffff"><span><b><span style="font-size: 10pt">Phần thưởng (Prize)</span></b></span></span></div>
<div style="margin: 0in 0in 0pt 0.5in; text-indent: -0.25in; line-height: normal; text-align: justify"><span style="color: #99ccff"><span style="font-size: 9pt">-<span style="font: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><span style="font-size: 10pt">Khi sự kiện kết th&uacute;c với kết quả ho&agrave;, 80% lệ ph&iacute; tham dự của tất cả người tham gia sẽ được trao ngẫu nhi&ecirc;n cho người chơi.</span></span></div>
<div style="margin: 0in 0in 0pt 0.5in; line-height: normal; text-align: justify"><span style="color: #99ccff"><span style="font-size: 10pt"><br>
  (V&iacute; dụ: tầng 1 c&oacute; 10 người tham dự =&gt; 25.000 x 10 x 0.8 = 200.000 zen)</span></span></div>
<div style="margin: 0in 0in 0pt 0.5in; line-height: normal; text-align: justify"><span style="color: #99ccff">&nbsp;</span></div>
<div style="margin: 0in 0in 0pt 0.5in; text-indent: -0.25in; line-height: normal; text-align: justify"><span style="color: #99ccff"><span style="font-size: 9pt">-<span style="font: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><span style="font-size: 10pt">Người sống s&oacute;t sẽ được thưởng 1 số m&oacute;n đồ (Bless, Soul, Chaos). Khi ở Chaos Castle cấp 1, ngo&agrave;i Bless, những m&oacute;n đồ c&oacute; cấp độ từ +4 đến +9 v&agrave; zen sẽ được rơi ra.</span></span></div>
<div style="margin: 0in 0in 0pt 0.5in; line-height: normal; text-align: justify"><span style="color: #99ccff">&nbsp;</span></div>
<div style="margin: 0in 0in 0pt 0.5in; text-indent: -0.25in; line-height: normal; text-align: justify"><span style="color: #99ccff"><span style="font-size: 9pt">-<span style="font: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><span style="font-size: 10pt">Khi bị ti&ecirc;u diệt, qu&aacute;i vật ở Chaos Castle sẽ kh&ocirc;ng rơi ra những m&oacute;n đồ tương ứng khi n&oacute; c&ograve;n ở b&ecirc;n ngo&agrave;i l&acirc;u đ&agrave;i.</span></span></div>
<div style="margin: 0in 0in 0pt 0.5in; text-align: justify"><span style="color: #99ccff">&nbsp;</span></div>
<div style="margin: 0in 0in 0pt 0.5in; text-indent: -0.25in; line-height: normal">
  <p style="text-align: justify"><span style="color: #99ccff"><span style="font-size: 9pt">-<span style="font: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><span style="font-size: 10pt">Bảng sau đ&acirc;y sẽ cho biết số lượng m&oacute;n đồ được rơi ra từ qu&aacute;i vật trong Chaos Castle.</span></span></p>
  <div align="center">
    <div align="center">&nbsp;</div>
    <div align="center">
      <center>
        <table cellspacing="0" cellpadding="0" width="493" border="0" style="width: 371pt; border-collapse: collapse">
          <colgroup>
            <col width="169" style="width: 127pt; mso-width-source: userset; mso-width-alt: 6180">
            <col width="78" style="width: 59pt; mso-width-source: userset; mso-width-alt: 2852">
            <col width="73" style="width: 55pt; mso-width-source: userset; mso-width-alt: 2669">
            <col width="85" style="width: 64pt; mso-width-source: userset; mso-width-alt: 3108">
            <col width="88" style="width: 66pt; mso-width-source: userset; mso-width-alt: 3218">
          </colgroup>
          <tbody>
            <tr height="20" style="height: 15pt; mso-yfti-irow: 0; mso-yfti-firstrow: yes">
              <td class="xl65" width="169" height="20" style="border-right: windowtext 0.5pt solid; border-top: windowtext 0.5pt solid; border-left: windowtext 0.5pt solid; width: 127pt; border-bottom: windowtext 0.5pt solid; height: 15pt; background-color: #92cddc; text-align: center"><font face="Verdana" color="#002060" size="2">&nbsp; </font><font face="Verdana" color="#002060" size="2">Chaos Castle tầng thứ</font></td>
              <td class="xl65" width="78" style="border-right: windowtext 0.5pt solid; border-top: windowtext 0.5pt solid; border-left: windowtext; width: 59pt; border-bottom: windowtext 0.5pt solid; background-color: #92cddc; text-align: center"><font color="#002060" size="2">Ngọc Bless</font></td>
              <td class="xl65" width="73" style="border-right: windowtext 0.5pt solid; border-top: windowtext 0.5pt solid; border-left: windowtext; width: 55pt; border-bottom: windowtext 0.5pt solid; background-color: #92cddc; text-align: center"><font color="#002060" size="2">Ngọc Soul</font></td>
              <td class="xl65" width="85" style="border-right: windowtext 0.5pt solid; border-top: windowtext 0.5pt solid; border-left: windowtext; width: 64pt; border-bottom: windowtext 0.5pt solid; background-color: #92cddc; text-align: center"><font color="#002060" size="2">Ngọc Chaos</font></td>
              <td class="xl65" width="88" style="border-right: windowtext 0.5pt solid; border-top: windowtext 0.5pt solid; border-left: windowtext; width: 66pt; border-bottom: windowtext 0.5pt solid; background-color: #92cddc; text-align: center"><font color="#002060" size="2">Zen</font></td>
            </tr>
            <tr height="20" style="height: 15pt; mso-yfti-irow: 1">
              <td class="xl65" height="20" style="border-right: windowtext 0.5pt solid; border-top: windowtext; border-left: windowtext 0.5pt solid; border-bottom: windowtext 0.5pt solid; height: 15pt; background-color: #92cddc; text-align: center"><font color="#002060" size="2">1</font></td>
              <td class="xl65" style="border-right: windowtext 0.5pt solid; border-top: windowtext; border-left: windowtext; border-bottom: windowtext 0.5pt solid; background-color: #92cddc; text-align: center"><font color="#002060" size="2">1</font></td>
              <td class="xl65" style="border-right: windowtext 0.5pt solid; border-top: windowtext; border-left: windowtext; border-bottom: windowtext 0.5pt solid; background-color: #92cddc; text-align: center"><font color="#002060" size="2">1</font></td>
              <td class="xl66" style="border-right: windowtext 0.5pt solid; border-top: windowtext; border-left: windowtext; border-bottom: windowtext 0.5pt solid; background-color: #92cddc; text-align: center"><font size="3">&nbsp;</font></td>
              <td class="xl68" width="88" rowspan="7" style="border-right: windowtext 0.5pt solid; border-top: windowtext; border-left: windowtext 0.5pt solid; width: 66pt; border-bottom: black 0.5pt solid; background-color: #92cddc; text-align: center"><font color="#002060" size="2">Dựa v&agrave;o cấp độ của qu&aacute;i vật</font></td>
            </tr>
            <tr height="20" style="height: 15pt; mso-yfti-irow: 2">
              <td class="xl65" height="20" style="border-right: windowtext 0.5pt solid; border-top: windowtext; border-left: windowtext 0.5pt solid; border-bottom: windowtext 0.5pt solid; height: 15pt; background-color: #92cddc; text-align: center"><font color="#002060" size="2">2</font></td>
              <td class="xl65" style="border-right: windowtext 0.5pt solid; border-top: windowtext; border-left: windowtext; border-bottom: windowtext 0.5pt solid; background-color: #92cddc; text-align: center"><font color="#002060" size="2">1</font></td>
              <td class="xl65" style="border-right: windowtext 0.5pt solid; border-top: windowtext; border-left: windowtext; border-bottom: windowtext 0.5pt solid; background-color: #92cddc; text-align: center"><font color="#002060" size="2">1</font></td>
              <td class="xl66" style="border-right: windowtext 0.5pt solid; border-top: windowtext; border-left: windowtext; border-bottom: windowtext 0.5pt solid; background-color: #92cddc; text-align: center"><font size="3">&nbsp;</font></td>
            </tr>
            <tr height="20" style="height: 15pt; mso-yfti-irow: 3">
              <td class="xl65" height="20" style="border-right: windowtext 0.5pt solid; border-top: windowtext; border-left: windowtext 0.5pt solid; border-bottom: windowtext 0.5pt solid; height: 15pt; background-color: #92cddc; text-align: center"><font color="#002060" size="2">3</font></td>
              <td class="xl65" style="border-right: windowtext 0.5pt solid; border-top: windowtext; border-left: windowtext; border-bottom: windowtext 0.5pt solid; background-color: #92cddc; text-align: center"><font color="#002060" size="2">1</font></td>
              <td class="xl65" style="border-right: windowtext 0.5pt solid; border-top: windowtext; border-left: windowtext; border-bottom: windowtext 0.5pt solid; background-color: #92cddc; text-align: center"><font color="#002060" size="2">1</font></td>
              <td class="xl66" style="border-right: windowtext 0.5pt solid; border-top: windowtext; border-left: windowtext; border-bottom: windowtext 0.5pt solid; background-color: #92cddc; text-align: center"><font size="3">&nbsp;</font></td>
            </tr>
            <tr height="20" style="height: 15pt; mso-yfti-irow: 4">
              <td class="xl65" height="20" style="border-right: windowtext 0.5pt solid; border-top: windowtext; border-left: windowtext 0.5pt solid; border-bottom: windowtext 0.5pt solid; height: 15pt; background-color: #92cddc; text-align: center"><font color="#002060" size="2">4</font></td>
              <td class="xl65" style="border-right: windowtext 0.5pt solid; border-top: windowtext; border-left: windowtext; border-bottom: windowtext 0.5pt solid; background-color: #92cddc; text-align: center"><font color="#002060" size="2">1</font></td>
              <td class="xl65" style="border-right: windowtext 0.5pt solid; border-top: windowtext; border-left: windowtext; border-bottom: windowtext 0.5pt solid; background-color: #92cddc; text-align: center"><font color="#002060" size="2">1</font></td>
              <td class="xl66" style="border-right: windowtext 0.5pt solid; border-top: windowtext; border-left: windowtext; border-bottom: windowtext 0.5pt solid; background-color: #92cddc; text-align: center"><font size="3">&nbsp;</font></td>
            </tr>
            <tr height="20" style="height: 15pt; mso-yfti-irow: 5">
              <td class="xl65" height="20" style="border-right: windowtext 0.5pt solid; border-top: windowtext; border-left: windowtext 0.5pt solid; border-bottom: windowtext 0.5pt solid; height: 15pt; background-color: #92cddc; text-align: center"><font color="#002060" size="2">5</font></td>
              <td class="xl65" style="border-right: windowtext 0.5pt solid; border-top: windowtext; border-left: windowtext; border-bottom: windowtext 0.5pt solid; background-color: #92cddc; text-align: center"><font color="#002060" size="2">1</font></td>
              <td class="xl65" style="border-right: windowtext 0.5pt solid; border-top: windowtext; border-left: windowtext; border-bottom: windowtext 0.5pt solid; background-color: #92cddc; text-align: center"><font color="#002060" size="2">2</font></td>
              <td class="xl66" style="border-right: windowtext 0.5pt solid; border-top: windowtext; border-left: windowtext; border-bottom: windowtext 0.5pt solid; background-color: #92cddc; text-align: center"><font size="3">&nbsp;</font></td>
            </tr>
            <tr height="20" style="height: 15pt; mso-yfti-irow: 6; mso-yfti-lastrow: yes">
              <td class="xl65" height="20" style="border-right: windowtext 0.5pt solid; border-top: windowtext; border-left: windowtext 0.5pt solid; border-bottom: windowtext 0.5pt solid; height: 15pt; background-color: #92cddc; text-align: center"><font color="#002060" size="2">6</font></td>
              <td class="xl65" style="border-right: windowtext 0.5pt solid; border-top: windowtext; border-left: windowtext; border-bottom: windowtext 0.5pt solid; background-color: #92cddc; text-align: center"><font color="#002060" size="2">1</font></td>
              <td class="xl65" style="border-right: windowtext 0.5pt solid; border-top: windowtext; border-left: windowtext; border-bottom: windowtext 0.5pt solid; background-color: #92cddc; text-align: center"><font color="#002060" size="2">2</font></td>
              <td class="xl67" style="border-right: windowtext 0.5pt solid; border-top: windowtext; border-left: windowtext; border-bottom: windowtext 0.5pt solid; background-color: #92cddc; text-align: center"><font color="#002060" size="2">&nbsp;</font></td>
            </tr>
            <tr height="20" style="height: 15pt">
              <td class="xl65" height="20" style="border-right: windowtext 0.5pt solid; border-top: windowtext; border-left: windowtext 0.5pt solid; border-bottom: windowtext 0.5pt solid; height: 15pt; background-color: #92cddc; text-align: center"><font color="#002060" size="2">7</font></td>
              <td class="xl65" style="border-right: windowtext 0.5pt solid; border-top: windowtext; border-left: windowtext; border-bottom: windowtext 0.5pt solid; background-color: #92cddc; text-align: center"><font color="#002060" size="2">2</font></td>
              <td class="xl65" style="border-right: windowtext 0.5pt solid; border-top: windowtext; border-left: windowtext; border-bottom: windowtext 0.5pt solid; background-color: #92cddc; text-align: center"><font color="#002060" size="2">4</font></td>
              <td class="xl67" style="border-right: windowtext 0.5pt solid; border-top: windowtext; border-left: windowtext; border-bottom: windowtext 0.5pt solid; background-color: #92cddc; text-align: center"><font color="#002060" size="2">&nbsp;</font></td>
            </tr>
          </tbody>
        </table>
      </center>
    </div>
  </div>
</div>